### ISSUE TITLE
Isn't working for me (sometimes) on 1.15.1

### ISSUE THREAD

**Issue by captam23** [KaptainWutax/SeedCracker#10]
I have gotten it to work but sometimes it doesn't. Like the image linked below, I tried 3 or 4 times to crack the seed for the world and it isn't working. Pretty sure I definitely explored enough. Along with this does the seedcracker not work well on worlds that have been modified by players already? Like if I went onto an SMP server already pretty old would this still work?

Read through the other issues, but this server was generated in 1.15.1 and doesnt have any 1.14 chunks or anything like that.

https://i.imgur.com/HQaABuW.png

**Comment by KaptainWutax** [comment]
There's some data that the seed cracker didn't like. Sometimes less is better-- you only need 5 combined structures and decorators. I'm still working on improving all the edge cases. Thanks for your report!
