### ISSUE TITLE
Forge Version

### ISSUE THREAD

**Issue by milutinke** [KaptainWutax/SeedCracker#103]
Some servers have started to block Fabric API (they identify it by some packet being sent to the server by the client) just because this mod exists.
Can we get a Forge version of the mod to get around this, if it of course possible to do it with the Forge API?

**Comment by InfoTeddy** [comment]
It would be far less work to make a mod that simply prevents that packet from being sent in the first place.

Also, blocking _all Fabric mods_?! Those servers are 100% scummy...

**Comment by KaptainWutax** [comment]
No forge version coming, fabric ftw.

**Comment by CDWimmer** [comment]
Forge support would make this usable in modded games such as the many FTB variants (in the case that the mods don't alter things that this relies on)

**Comment by InfoTeddy** [comment]
Yes it would. The mod would also have to probably be backported to an earlier version of Minecraft, which means even more work not only rewriting but testing the code than would already have to be done to port it to Forge.

**Comment by CDWimmer** [comment]
Forge is on 1.16.5.
