### ISSUE TITLE
Dungeon cracker returning [0] on some servers

### ISSUE THREAD

**Issue by Garfield100** [KaptainWutax/SeedCracker#104]
![image](https://user-images.githubusercontent.com/5878721/93016658-308a0180-f5c3-11ea-910d-6638f772b446.png)

After "short-cutting to dungeons" it finds several structure seeds, [0] among them.
When it then looks for world seeds it just returns [0] and finishes, as can be seen in the screenshot.
I am far out enough that everything is newly generated.
Let me know if you need more info.

**Comment by KaptainWutax** [comment]
Cause the seed is literally 0. :p
