### ISSUE TITLE
Disabling Emerald Ore doesn’t work.

### ISSUE THREAD

**Issue by ekersey18** [KaptainWutax/SeedCracker#105]
I need to disable using emerald ore to get bits because a server I play on unnaturally generates them, however the /seed finder type command doesn’t work.  I don’t know if it matters but I’m using the 1.16.2 mod on a 1.16.3 server.

**Comment by bat1rya** [comment]
Is it possible that we can 1.16.2 works on server 1.16.3 how did you do it

**Comment by ekersey18** [comment]
I just put the jar in the mods folder with the only version of fabric being 1.16.3.  Btw the reason it wouldn’t work was because it wasn’t highlighted the cracker needed to be off to disable emerald ore.
