### ISSUE TITLE
Game Crashing

### ISSUE THREAD

**Issue by Fex47** [KaptainWutax/SeedCracker#107]
[crash-2020-09-29_09.54.41-client.txt](https://github.com/KaptainWutax/SeedCracker/files/5299479/crash-2020-09-29_09.54.41-client.txt)

**Comment by InfoTeddy** [comment]
It says you're using v0.2.0-beta. Does this crash happen on the [v0.2.2-beta release](https://github.com/KaptainWutax/SeedCracker/releases/tag/v0.2.2-beta)?

**Comment by KaptainWutax** [comment]
Yea, use latest.
