### ISSUE TITLE
Finished dungeon search with no seeds.

### ISSUE THREAD

**Issue by GurkisXD** [KaptainWutax/SeedCracker#108]
Somewhy the seed cracker doesn't work. I have tried with every single category but nothing works.
The dungeons are intact

![Uploading 2020-09-30_21.09.21.png…]()

**Comment by InfoTeddy** [comment]
Your screenshot doesn't embed.

First, did you enable the dungeons finder? If so, then what kind of configuration does the map you're playing on have? Is it all 100% vanilla? Does one seed control all of the generation of the overworld, or are there multiple seeds for structures, biomes, etc.?
