### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by Sgt-Schultz** [KaptainWutax/SeedCracker#11]
Thanks for the mod! Finding the seed took no time at all. I have used the seed with programs that find the locations of various structures, but I wondered if there could be a program that could find certain uncraftable loot in chests (like enchanted apples). From what I understand the loot is generated based off the seed, so in theory this should be something that could be done. I have 0 experience with minecraft mods/minecraft code and I can't find anything useful online to answer my questions. Do you have any suggestions/links to anything that could help me? I do have some programming experience. Thanks again for the wonderful program!

**Comment by KaptainWutax** [comment]
Funnily enough, I have added a loot finder to the seed cracker for seed finding purposes. But it's not easy to use unless you have experience with the Minecraft codebase and modding.

**Comment by Sgt-Schultz** [comment]
I don't mean a loot finder mod that scans for chests in your area in game. I was talking about something like this: https://chunkbase.com/apps/buried-treasure-finder
But it looks for loot chests that generate golden apples, which I think can be done because loot is determined by seed. A program that can take the seed and return locations of enchanted apples that is. This would be incredible useful since enchanted apples are rare, uncraftable and extremely useful.  I have yet to find any type of program that can find items like this.

**Comment by KaptainWutax** [comment]
Yes, the seed cracker has an api that can look for a seed like that (https://github.com/KaptainWutax/SeedCracker/blob/master/src/main/java/kaptainwutax/seedcracker/cracker/ChestLootData.java). It hasn't been implemented in-game but I have used it to search seeds with good buried treasure loot.

**Comment by Sgt-Schultz** [comment]
So you can use that to locate loot in a world? I am in a server and I have the seed and I want to locate enchanted apples in loot chests.

**Comment by KaptainWutax** [comment]
Yes, if you use the API right.
