### ISSUE TITLE
How to make it work on optifine

### ISSUE THREAD

**Issue by Nsoz1** [KaptainWutax/SeedCracker#110]
Hello i am wondering on how to make it work on optifine and is the 1.16.2 version compatible with 1.16.3?

**Comment by jontyms** [comment]
@Nsoz1 this should work for optifine [here](https://www.curseforge.com/minecraft/mc-mods/optifabric). I have not seen if this mod is specifically compatible.  The rendering might break. I don't know if this mod works for 1.16.3

**Comment by Nsoz1** [comment]
I tried already with optifabric but once i try to join a world it just crashes and gives a random error. And i cant run the mod without optifine because my pc cant handle it without.

**Comment by jontyms** [comment]
Are you trying to run this on 1.16.2 or 1.16.3, try with optifabric 1.16.2. If that doesn't work try running it with [soduim](https://www.curseforge.com/minecraft/mc-mods/sodium)

**Comment by Nsoz1** [comment]
Ill try that thanks i will let you know if it worked or not

**Comment by Nsoz1** [comment]
Yeah so i got the mod to run smoothly but it doesnt seem to work on 1.16.3 so ima have to wait for an update i think :P thanks anyway jontyms

**Comment by Nsoz1** [comment]
So i just did a bit of searching and i saw that it does work for 1.16.3 but apperently not with fps enhancing mods added so would you please find the seed for my server please. If you can this is the ip if you would like i can pay you 50 cents on paypal xD 164.132.233.112:25594

**Comment by KaptainWutax** [comment]
It works in 1.16.3.

**Comment by Nsoz1** [comment]
I tried it, it does not function

**Comment by Nsoz1** [comment]
With optofine

**Comment by KaptainWutax** [comment]
Blame optifine-- go use a good mod like sodium instead.
