### ISSUE TITLE
ModMenu Compatibility [enhancement]

### ISSUE THREAD

**Issue by FourInchKnife** [KaptainWutax/SeedCracker#111]
Please make this mod compatible with ModMenu, so that I can change the default option of the renderer.

**Comment by 19MisterX98** [comment]
https://github.com/19MisterX98/seedcracker12/releases

**Comment by KaptainWutax** [comment]
Maybe one day

**Comment by KaptainWutax** [comment]
Actually, never mind. I'm not adding the renderer settings to ModMenu.
