### ISSUE TITLE
Is there a 1.16.3 release date?

### ISSUE THREAD

**Issue by comotose** [KaptainWutax/SeedCracker#112]
Is there a 1.16.3 release date and will there be a mod for it?

**Comment by Neffc** [comment]
The 1.16.2 version works for 1.16.3.

**Comment by comotose** [comment]
> The 1.16.2 version works for 1.16.3.

i dont know the problems is, but i have the same seed in the overworld, nether and end

**Comment by KaptainWutax** [comment]
It works in 1.16.3.

**Comment by comotose** [comment]
> It works in 1.16.3.

is there a way to solve the problem with the same seed in nether and overworlde? Plus both are wrong

**Comment by KaptainWutax** [comment]
Do you even know how seed work?

**Comment by comotose** [comment]
Most likely no

**Comment by KaptainWutax** [comment]
Why are you using SeedCracker if you don't? Seeds are SUPPOSED to be the same yes.

**Comment by comotose** [comment]
Sorry, but I didn't understand what you said (google translator). I just want the seed cracker to work.. Really sorry for wasting your time

**Comment by comotose** [comment]
If that I have a different seed even in a singleplayer. Made 10 worlds, all different. It never happened before

**Comment by 19MisterX98** [comment]
different worlds have different seeds. overworld nether and end have the same seed(modded may be different).

**Comment by comotose** [comment]
I know that worlds have different seeds. And I'm not sure about the same seed for overworld, nether and end. But what you said won't solve my problem
