### ISSUE TITLE
Finished search with no results.

### ISSUE THREAD

**Issue by 9alexyt5** [KaptainWutax/SeedCracker#113]
It keeps happening and idk what to do...
![Screenshot_39](https://user-images.githubusercontent.com/55896708/95660553-fb70c080-0b28-11eb-925a-e4473622b6f8.png)
![Screenshot_40](https://user-images.githubusercontent.com/55896708/95660554-fc095700-0b28-11eb-95c1-e074e591f87a.png)

**Comment by KaptainWutax** [comment]
Make sure you're only using 1.16 features, that the server is not running paper, etc etc etc

**Comment by 9alexyt5** [comment]
And can i download part of this world using another mod, run it on vanilla and will it find me this seed?
