### ISSUE TITLE
Multiplayer servers

### ISSUE THREAD

**Issue by Thijs747** [KaptainWutax/SeedCracker#115]
Hi, does this mod work on servers? I'm on a Paper server trying to find the seed, but when doing so, I got no output at all. When checking the collected bits, it says it's at 956 out of 32 bits. I've cleared it a few times but with no result.

**Comment by Thijs747** [comment]
Oh yeah, it does fetch the hashed world seed tho. Maybe a command that redisplays the seed would be a nice addition?

**Comment by KaptainWutax** [comment]
Use the dungeon method.
