### ISSUE TITLE
seed found but with different biome

### ISSUE THREAD

**Issue by JD-2020** [KaptainWutax/SeedCracker#117]
Hi, When I run seedcracker on a server (1.16.3), I found the seed. but when I use the seed to create a single player map (on 1.16.3) I notice some biomes are different (e.g. desert instead of forest or mountain, not sure how to identify biomes ¯\\\_(ツ)\_/¯), although the terrain and majority of the biomes are the same. I found the seed by using the dungeon method since I don't have access to the end portal.

**Comment by KaptainWutax** [comment]
Is the server using large biomes?

**Comment by JD-2020** [comment]
The server is not using large biomes. not sure if this is relevent but I heard from the server admin that structure generation was only recently enabled (it was disabled during the world creation) using NBTEditor.

**Comment by KaptainWutax** [comment]
If SeedCracker gives you a seed then it can't be a false positive.
