### ISSUE TITLE
Is it possible to crack with only the nether and end?

### ISSUE THREAD

**Issue by owowhat** [KaptainWutax/SeedCracker#119]
Not sure where else to ask this, but I'm trying to crack the seed of a server, but it has an anti-Xray plugin which I'm pretty sure entirely breaks the seed finding. Since it doesn't affect the end or nether, is it possible to use only those dimensions?

**Comment by lectelu** [comment]
just turn off emerald ore then do /seed data clear and start exploring world, then go to end to get pillars
you can also do
turn off emerald ore 
turn off mod
relog
turn on mod
start exploring world
when you have high amount of bits go to end to get pillars
