### ISSUE TITLE
buried treasure & ship wrecks not highlighted

### ISSUE THREAD

**Issue by end-user** [KaptainWutax/SeedCracker#120]
At some point, buried treasure and ship wrecks stopped getting highlighted (xray).  Did this get removed?

**Comment by end-user** [comment]
Also jungle temples.

**Comment by KaptainWutax** [comment]
This was never removed.

**Comment by InfoTeddy** [comment]
I assume you're on a multiplayer server with these structures. If you could grab a world download (using a mod) of the structures that aren't being identified, and then upload it, that would be helpful.
