### ISSUE TITLE
Port to 20w45a?? java.lang.NoSuchMethodError: net.minecraft.class_287.method_1328(ILnet/minecraft/class_293;)V

### ISSUE THREAD

**Issue by hashblen** [KaptainWutax/SeedCracker#123]
Hi, when putting this mod into 20w45a (I know this is for 1.16.4 but I wanted to test), it crashes, but only in multiplayer.
 crash report : https://pastebin.com/zaxEjQqj
I wanted to ask, why is it so complicated to port a mod from a version to the next one, and if it would be possible for me or anyone to patch this. thx ;)

**Comment by hashblen** [comment]
hi, im dumb. im taking the source code and migrating the mapping and dependencies with https://modmuss50.me/fabric.html?&version=20w45a

**Comment by KaptainWutax** [comment]
I was just porting it to check out the snapshots. You can build the latest commit.

**Comment by hashblen** [comment]
thx a lot :)
i'll try in 10 minx because gradle 6.5 is still downloading (I have max 100kB/s)

**Comment by hashblen** [comment]
while i'm at it, how and where do you find the new changes in mc's code ? i mean from 1.16.4 and 20w45a

**Comment by hashblen** [comment]
when I build it, it says 
> Failed to provide com.mojang:minecraft:20w45a : null
if you built it, can u send it to me ?

**Comment by hashblen** [comment]
finally

built it, testing rn
