### ISSUE TITLE
How do I fetch Seeds from Multiplayer Servers?

### ISSUE THREAD

**Issue by LaggyNacho** [KaptainWutax/SeedCracker#125]
How do I fetch Seeds from Multiplayer Servers?

I only got the fetched hashed world seed. But how do I get the actual world seed? 
"/seed" does not work on multiplayer server.

It is an 1.16.4 Vanilla Server (no plugins and no mods).

**Comment by MAqib123** [comment]
i managed to find overworld seed which perfect but I'm unable to find end seed.

**Comment by LaggyNacho** [comment]
I managed to solve this problem by my own. Everything works fine now.
