### ISSUE TITLE
question : port to 20w45a never finds any seed even with only nether and end where generation didn't change

### ISSUE THREAD

**Issue by hashblen** [KaptainWutax/SeedCracker#126]
hi, I tried the port to 20w45a, but it never finds any seed even with only nether and end where generation didn't change...
someone knows why ?
thanks :)

**Comment by brandonplank** [comment]
I can confirm there are issues, Lets say the server has xray protection, and you turn off Emeralds, it will still load them :/

**Comment by hashblen** [comment]
Why do I see emeralds then ? It highlights true emeralds

**Comment by brandonplank** [comment]
I’m just saying if you turn off the emerald ore option, it will still load them.

**Comment by KaptainWutax** [comment]
Bold of you to assume generation didn't change... just wait for the update I guess lol
