### ISSUE TITLE
Question: Versions supported by dungeon finder?

### ISSUE THREAD

**Issue by datatags** [KaptainWutax/SeedCracker#128]
The server I'm using this on has worlds generated on versions all the way back to 1.8.  My question is, will the dungeon trick work all the way back then?  On the minecraft wiki dungeon history, there aren't any changes since 1.8 except about loot tables, but it doesn't seem to be working as I'm trying it on a 1.13 world.  I did find the seed of the 1.15 world, but it took many dungeons before it found the seed.  Any insight?  Thanks!

**Comment by KaptainWutax** [comment]
You need to use dungeons generated in the release version. If you're using the 1.15 jar then you gotta find dungeons generated in 1.15. If you're using the 1.16 jar then you gotta find 1.16 dungeons, etc.

**Comment by datatags** [comment]
Ok thanks!
