### ISSUE TITLE
Unable to get cracker working

### ISSUE THREAD

**Issue by DyteSprite** [KaptainWutax/SeedCracker#129]
On multiple different multiplayer servers (version 1.16.3), I keep getting the message "ur bad, git gud syntax" upon trying to run any seedcracker command. Demonstrated in the following [GIF](https://i.gyazo.com/f61528965619370e9b915e26b7466d19.gif)

**Comment by SirAlmighty-Shibe** [comment]
youre getting a syntax error, you gotta press tab again for the last setting which is "on" or "off"

**Comment by DyteSprite** [comment]
Oops, forgot about that. Thanks for the help!
