### ISSUE TITLE
No results.

### ISSUE THREAD

**Issue by Frustrated-Programmer** [KaptainWutax/SeedCracker#133]
So I'm playing on a 1.16.3 spigot/paper server (idrk but can confirm if needed), that runs with these plugins:
```AdvancedWarn, ArmorStandEditor, BlameGareth, ChunkLagChecker, Citizens, CommandHook, CoreProtect, DeluxeTags, DiscordSRV, Essentials, EssentialsChat, EssentialsProtect, EssentialsSpawn, GriefPrevention, ID-Library, LibsDisguises, LuckPerms, Mentions, PacketListenerApi, PlayerHeads, PremiumVanish, ProtocolLib, Shopkeepers, SkQuery, Skript, SlimeBucket, SmoothSleep, StaffChat*, Vault, ViaVersion, WorldEdit, WorldGuard```

I'm just informing you just in case, as the more info the merrier!

I've read the prev issues and learned on spigot/paper they use a seperate seed for the end versus overworld so to find overworld seed I need todo dungeon mode.

I've flown to un-generated chunks to ensure everything is how they were supposed to generate and even checked a few of the dungeons to ensure they exist and isn't modded/faked

But no matter what/how I do this I always somehow end up with: `Finished search with no results.`

Recently I've found an area with multiple dungeons so I get this:
```
Short-cutting to dungeons...
Found structure seed [238234512010950].
Found structure seed [238425472662950].
Found structure seed [192268961239793].
Found structure seed [146340265545060].
Found structure seed [181352853056836].
Found structure seed [131865358126447].
Found structure seed [75780384601288].
Found structure seed [243186859184451].
Found structure seed [33440334320515].
Found structure seed [279619796965795].
====================================
Looking for world seeds...
Finished search with no results.```

the biggest line of structure seeds so far, but still no world seed.
I do have emerald ore's off (even tho it appears so far that every emerald ore the cracker sees, exists. And I've made sure dungeons are on.

Any suggestions what more I can do to try to find the seed?

**Comment by KaptainWutax** [comment]
Use dungeons generated in 1.16.
