### ISSUE TITLE
ayudame please benevolent developer

### ISSUE THREAD

**Issue by jahsef** [KaptainWutax/SeedCracker#135]
I used chunkbase to find bastions, end cities, and nether fortresses but they are never in those locations.
Chunkbase only seems to work in the overworld.
Server is Tuinity 1.16.4 with these plugins
![image](https://user-images.githubusercontent.com/69409073/100303054-862e4300-2f50-11eb-84cd-b589b3f99585.png)

**Comment by KaptainWutax** [comment]
try https://github.com/hube12/MineMap, if it doesn't work then I can't do anything for you.
