### ISSUE TITLE
"Get Gud Syntax" Problem

### ISSUE THREAD

**Issue by Idontknowwhattonamethis** [KaptainWutax/SeedCracker#136]
Whenever I put a command in to find the seed, EVEN IF I USE TAB TO AUTO-COMPLETE, it always comes up with the message "Get Gud Syntax" (1.16.4)

**Comment by Idontknowwhattonamethis** [comment]
![image_2020-11-28_112529](https://user-images.githubusercontent.com/75181456/100524369-6bd0b100-316c-11eb-9c3c-0a664b791720.png)

**Comment by KaptainWutax** [comment]
Set it to ON/OFF
