### ISSUE TITLE
Allow for manual marking of structures

### ISSUE THREAD

**Issue by silentstormm** [KaptainWutax/SeedCracker#137]
Structures aren't detected on servers, and I get why that happens, but there should be a way to manually mark things like spawners, desert temples, end portals etc.

**Comment by silentstormm** [comment]
Nevrmind, I don't get it, a desert well got detected but not two pyramids and a witch hut

**Comment by KaptainWutax** [comment]
The structures have to be intact.

**Comment by silentstormm** [comment]
They were perfectly intact (just generated in fact) and still were not recognised
