### ISSUE TITLE
Is there a way to retain data after relogging?

### ISSUE THREAD

**Issue by silentstormm** [KaptainWutax/SeedCracker#138]
My internet is a bit unreliable, so being online on a server continuously for a long time while I run around and find all the different structures is kinda impossible, but if I understand correctly, after relogging the data is cleared. Is there a way to store it more permanently so I could for example explore a bit, take a break, and come back later without needing to collect the data from scratch?

**Comment by KaptainWutax** [comment]
Nope, sorry, and I don't plan to.
