### ISSUE TITLE
Seed cracker does not show seed.

### ISSUE THREAD

**Issue by Christiano300** [KaptainWutax/SeedCracker#139]
I often have the following problem:
It says fetched hashed world seed when I join the world. But it wont show me the seed! If I write /seed data bits it says, that more then 32 bits are collected. Once, there were over 1000 bits collected. I scrolled through the entire chat, but even above the "Fetched hashed world seed", I couln´t find the seed. I tried turning the seed cracker on and off, clearing the bits and collecting new ones, rejoin the world, restart Minecraft, etc. If I try /seed it says I don´t have the permission to do this. If this Issue won´t get fixed, the seed cracker is useless for me.

**Comment by Wostoast** [comment]
you need to travel into the end and load the obby pillars for it to start doing stuff. its not an option since the pillars are key points when getting the seed.
