### ISSUE TITLE
Seed cracking with multiple worlds

### ISSUE THREAD

**Issue by friendlytherapist** [KaptainWutax/SeedCracker#14]
Im trying to seed crack a survival servers seed but the problem i face is that when logging into the server (from the minecraft multiplayer screen) I will start in the lobby with a choice of specific servers to connect to (skyblock, survival, creative, ect.) Im guessing the seed cracker is using the lobbys biomes ect and it is messing up the survival seed since they are different worlds. How do i disable all logging until i am on the server i wish to crack?

**Comment by KaptainWutax** [comment]
Sorry about that, there's is currently no way to delete the collected data. I'll work on implementing it.

**Comment by noodlychezzy** [comment]
bump
please implement it
maybe when you start playing, it doesnt start searching until you enter a command eg.
/seed finder ON
this way it would start searching when you want

**Comment by KaptainWutax** [comment]
I have implemented a way to clear data `/seed data clear` a while ago but haven't made a release. You can build the mod yourself if you absolutely need it.

**Comment by noodlychezzy** [comment]
im stupid and have no clue how to do so

**Comment by noodlychezzy** [comment]
If I do the command, will it clear all the data and then start to collect data again, or will it not collect any data until you relog?

**Comment by noodlychezzy** [comment]
i built the mod but now when i open the game, the launcher closes as it should but the game doesnt open. java is open in task manager though

**Comment by KaptainWutax** [comment]
LOL yea it's bruteforcing seeds for the infinity update, forgot to comment that out. Gimme a sec to fix it in the repo.

**Comment by noodlychezzy** [comment]
oh okay thanks
fuck it took me 4 hours to figure how to build

**Comment by KaptainWutax** [comment]
Fixed it, you can pull now. :D

**Comment by noodlychezzy** [comment]
thank you, can you answer my question too
If I do the command, will it clear all the data and then start to collect data again, or will it not collect any data until you relog?

**Comment by KaptainWutax** [comment]
Clears all the data and starts again.

**Comment by noodlychezzy** [comment]
thanks

**Comment by KaptainWutax** [comment]
With version v0.1.0-beta and onwards this is now supported through `/seed data clear`.
