### ISSUE TITLE
Weird ore gen

### ISSUE THREAD

**Issue by Wostoast** [KaptainWutax/SeedCracker#140]
I need to get the seed from a server I'm on but cant since this uses emerald ore as a point. I wouldn't mind it, if it weren't for the fact I cant get a world seed because of the weird ore gen they have. (ores no longer spawn in veins and now spawn randomly at any y-level.) help? ;-;

**Comment by Catchears** [comment]
you can do `/seed finder type EMERALD_ORE OFF`
