### ISSUE TITLE
Finds wrong seed

### ISSUE THREAD

**Issue by turret001** [KaptainWutax/SeedCracker#146]
so, I created a singleplayer world with seed 4331204936418704080 and when I joined it, this is what seedcracker told me. 

![image](https://user-images.githubusercontent.com/24281147/102698135-2758a280-424c-11eb-9d24-d2d62b6ff82a.png)

how can we debug this and find the issue or am I doing something wrong :/

Minecraft Version: 1.16.4 / Fabric

**Comment by 645862** [comment]
That is the hashed world seed. You have to move around a bit in the world for it to start working.

**Comment by turret001** [comment]
I see, how many 'bits' do I need? will it automatically output the seed into chat?

**Comment by 645862** [comment]
I just learned myself actually that you need to go to the end for the end pillars. If you move around enough and go to the end, it should output the seed into the chat. Yes you can be as far away from spawn as you want to run it.

**Comment by turret001** [comment]
well it failed for some reason :/ it took some time to process but this is what I got in the end
![image](https://user-images.githubusercontent.com/24281147/102701299-ba063b00-4266-11eb-93c6-820f8189584e.png)

**Comment by huntergroton** [comment]
Same thing happening to me. No clue what I'm doing wrong. 
![Capture](https://user-images.githubusercontent.com/76274809/102707100-187ee980-4266-11eb-9e1b-21e06275d047.PNG)

**Comment by Bluedragonplayz2** [comment]
hmmm is it possible that spigot world generation could be at fault?

**Comment by 645862** [comment]
yeah that's probably it.
Try going into a singleplayer world and see if it works.

**Comment by KaptainWutax** [comment]
Make sure you're only getting data from 1.16 generated chunks. If this is a paper server the end pillars won't work so use dungeons instead.
