### ISSUE TITLE
ur bad, get gud syntax

### ISSUE THREAD

**Issue by Yuuto0** [KaptainWutax/SeedCracker#148]
I'm trying to find the world seed on a multiplayer 1.16.2 spigot world and whenever I try /seed finder type DUNGEON, it always says ur bad get gud syntax, is there a fix to this?

**Comment by DarkReaper231** [comment]
Just use tab for prediction as the type names seems to be renamed from what is written on github README

**Comment by Tiebe** [comment]
@Yuuto0 add ON or OFF at the end
