### ISSUE TITLE
Interference

### ISSUE THREAD

**Issue by Bluedragonplayz2** [KaptainWutax/SeedCracker#150]
could the cracker be written to recognise anti x-ray
cause all it sees is an impossible amount of ores and eventually led to a failed crack
also, some spigot would generate the end nether and overworld with separate seeds can the cracker use only data from the overworld / end / nether?

**Comment by KaptainWutax** [comment]
You can get the OW and end but not the nether. And no, I ain't gonna offer direct support for modded servers. You can disable the ore finder.
