### ISSUE TITLE
Fetched 2 different hashed world seeds / world seed 0

### ISSUE THREAD

**Issue by succsucc23** [KaptainWutax/SeedCracker#151]
![2021-01-06_02 00 26](https://user-images.githubusercontent.com/77032458/103716321-079ed980-4fc3-11eb-8286-ee6ba8da694f.png)
Logged in got two world seeds, failed to find seed and proceeds to output 0 as correct world seed. I tried relogging and reentering the dimension (went into a nether portal and back) with limited success: I didn't get 0 as a hashed seed but the end result was still 0.
I also tried doing this further away (about 600 blocks from the first attempt) but got the same results.
Tested this in singleplayer and on my private server and it worked perfectly, just not this time.

**Comment by KaptainWutax** [comment]
It means the seed IS 0. Check it in singleplayer.

**Comment by succsucc23** [comment]
I checked but neither the structures nor the biomes/landscapes are correct. I haven't tried the old method with the end pillars but the end is currently inaccessible. If you need more information please let me know.

**Comment by DoomRater** [comment]
A technical note: a world seed of 0 means you must enter in something that hashes to 0- entering a world seed of 0 will not produce a world with a seed of 0.
