### ISSUE TITLE
Is there a way to use this for older versions of Minecraft

### ISSUE THREAD

**Issue by Selimbits** [KaptainWutax/SeedCracker#152]
Hi, I've been trying to find a way to crack the seed of a 1.7.10 minigame server without /seed. Your project is the closest I've gotten to doing it but there isn't a version of SeedCracker that is suitable for my needs, is there any way that I can use this for 1.7.10 and older? I don't know if this is the right place to write it, I'm new to GitHub.

PS: There are strongholds and natural terrain to work wiith even though it's a minigame server.

@KaptainWutax

**Comment by KaptainWutax** [comment]
Older versions are not supported.

**Comment by CelestialStreamer** [comment]
What kind of work would it take to support other versions of Minecraft? I know there are many multiplayer servers still at 12.2.2 and would be useful for some. This project seems likely to only every support the current version of Minecraft so if I was serious I would likely need to fork the repo. (Though, would you accept PRs if someone added support for other versions of Minecraft?) What resources exist to help one learn how to reverse-engineer seeds for different Minecraft versions?

**Comment by KaptainWutax** [comment]
A good amount of work. I wouldn't take PRs for it but the code is MIT so feel free to create your own public repo for it.
