### ISSUE TITLE
probably new counter-measures 

### ISSUE THREAD

**Issue by Meemoryk** [KaptainWutax/SeedCracker#155]
Hello, 
i was testing this mod on server "atomicmelter.sytes.net" and it seems that from some kind of reason it is not working,
is it possible that Server made some preventive measures ? 
server version: 1.16.4

It's working in single player and also on diff server. 

by not working i mean, 
that mod can't see almost none structures like End City, Buried threasures and so on..
but mod can correctly identify biomes. 

by many tries i was able to identify world seed but not End seed 
( it's not possible seens End city and EndGateway are not visible for mod ) 

Tried to download the game again and instal latest Fabric ( 1.16.4 - loader version 0.11.0 )  + latest fabric api ( fabric-api-0.29.3+1.16 ) the latest seedCracker mod was donwloaded as well ( seedcracker-0.2.3-beta ). 
still the same issue. 

Can you please check ?

**Comment by Mancek** [comment]
I have the same problem, also I found dungeons but mod doesn't register them, it only registers biomes, emerald ores and end pillars but can't calculate seed, even with more than 100k data bits. Also this server uses hub when you login and than you pick if you want to play on survival, factio etc. Is it possible that it gets wrong hashed seed, if yes how can I fix it?

**Comment by NanJack1998** [comment]
the same problem i'v met,i'v already found 3 dungeon and it still can't cauculate the seed

**Comment by diocrap** [comment]
> the same problem i'v met,i'v already found 3 dungeon and it still can't cauculate the seed



> I have the same problem, also I found dungeons but mod doesn't register them, it only registers biomes, emerald ores and end pillars but can't calculate seed, even with more than 100k data bits. Also this server uses hub when you login and than you pick if you want to play on survival, factio etc. Is it possible that it gets wrong hashed seed, if yes how can I fix it?



> Hello,
> i was testing this mod on server "atomicmelter.sytes.net" and it seems that from some kind of reason it is not working,
> is it possible that Server made some preventive measures ?
> server version: 1.16.4
> 
> It's working in single player and also on diff server.
> 
> by not working i mean,
> that mod can't see almost none structures like End City, Buried threasures and so on..
> but mod can correctly identify biomes.
> 
> by many tries i was able to identify world seed but not End seed
> ( it's not possible seens End city and EndGateway are not visible for mod )
> 
> Tried to download the game again and instal latest Fabric ( 1.16.4 - loader version 0.11.0 ) + latest fabric api ( fabric-api-0.29.3+1.16 ) the latest seedCracker mod was donwloaded as well ( seedcracker-0.2.3-beta ).
> still the same issue.
> 
> Can you please check ?

Im pretty sure that this rep doesn't work on paper spigot because they didn't implement the new simple seed obfuscation for dungeons. Not sure what that is exactly, but server running on paper wont work.

**Comment by NanJack1998** [comment]
> 
> 
> > the same problem i'v met,i'v already found 3 dungeon and it still can't cauculate the seed
> 
> > I have the same problem, also I found dungeons but mod doesn't register them, it only registers biomes, emerald ores and end pillars but can't calculate seed, even with more than 100k data bits. Also this server uses hub when you login and than you pick if you want to play on survival, factio etc. Is it possible that it gets wrong hashed seed, if yes how can I fix it?
> 
> > Hello,
> > i was testing this mod on server "atomicmelter.sytes.net" and it seems that from some kind of reason it is not working,
> > is it possible that Server made some preventive measures ?
> > server version: 1.16.4
> > It's working in single player and also on diff server.
> > by not working i mean,
> > that mod can't see almost none structures like End City, Buried threasures and so on..
> > but mod can correctly identify biomes.
> > by many tries i was able to identify world seed but not End seed
> > ( it's not possible seens End city and EndGateway are not visible for mod )
> > Tried to download the game again and instal latest Fabric ( 1.16.4 - loader version 0.11.0 ) + latest fabric api ( fabric-api-0.29.3+1.16 ) the latest seedCracker mod was donwloaded as well ( seedcracker-0.2.3-beta ).
> > still the same issue.
> > Can you please check ?
> 
> Im pretty sure that this rep doesn't work on paper spigot because they didn't implement the new simple seed obfuscation for dungeons. Not sure what that is exactly, but server running on paper wont work.

it's just a vanilla server

**Comment by diocrap** [comment]
@Mancek @Meemoryk I’ve tried several times. Make sure the dungeons you find aren’t traced with one block. A proper dungeon should be traced by the outline of the room and the spawner itself. Stay in one place until it just declares that you can’t find the seed. After that just relog and try again. It worked for me but it took a little bit of time.

**Comment by NanJack1998** [comment]
the case i met,it only trace dungeon itself not with the room's outline,is it any differences?

**Comment by diocrap** [comment]
> the case i met,it only trace dungeon itself not with the room's outline,is it any differences?

@NanJack1998 in neils explanation video https://youtu.be/aUuPSZVPH8E at the time of 8:05 you can see how a dungeon should be displayed and right after that he shows what i mean by a single block outlined dungeon (which is no good). If you see the first kind of dungeon, it should begin calculating seed right away. If you see the second kind of outline (the bad one) pretty much nothing happens.

**Comment by Mancek** [comment]
So I got it working on this server. Server was created on 1.1.6.4 version so version wasn't the problem also world generation wasn't modified by plugins or anything. Not sure why this happend but when I loaded new chunks seed was cracked in few seconds. So if you have the same problem try going far far away in one direction so you load new chunks and it should work.

**Comment by zykrahgaming** [comment]
see #58
