### ISSUE TITLE
End dimension

### ISSUE THREAD

**Issue by ArthyArrow** [KaptainWutax/SeedCracker#156]
Is it possible to crack the seed without the end if I find enough details, It is impsossible to go to end in the server I am currently playing and they have a prize for anyone that manages to find the seed.

**Comment by succsucc23** [comment]
It is possible if you find a dungeon but you have to enable that first: /seed finder type DUNGEON ON

**Comment by ArthyArrow** [comment]
Even though it is on and I am sitting on top of the spawner it doesnt realize the dungeon

**Comment by ArthyArrow** [comment]
Got it to work but it couldn't find the seed :(

**Comment by ArthyArrow** [comment]
And now even though it finds the dungeon it doesnt search for the seed, what an unlucky guy I am

**Comment by NanJack1998** [comment]
even though i found 3 dungeons and i enter the end ,it still find no seed

**Comment by KaptainWutax** [comment]
You need to find a dungeon where the floor is highlighted.
