### ISSUE TITLE
Not Working On Latest Paper Version

### ISSUE THREAD

**Issue by RocketNinja15** [KaptainWutax/SeedCracker#157]
Hello! 

On the latest paper mc versions... This does not work

**Comment by Cr3atable** [comment]
I tested this on an unconfigured Paper server with the latest Paper version at this time (Build $468) and had successful results. Maybe the server you tried this on has Paper's ore obfuscation settings on?

**Comment by KaptainWutax** [comment]
Yea it works on paper.
