### ISSUE TITLE
Seed is incorrect

### ISSUE THREAD

**Issue by Demon-tk** [KaptainWutax/SeedCracker#160]
On Minecraft 1.16.4
The latest version of the mod
Fabric loader 0.11.0-1.16.4

Seed and Fetched hashed world seed and different

Any ideas?

**Comment by diocrap** [comment]
@Demon-tk ignore the fetched hashed world seed. The real seed is when it displays “found world seed [seed number]”

**Comment by Demon-tk** [comment]
Gotcha, even after it says it's collected 100/32 bits? Is there any configuration I have to do, I have left the settings at default.

**Comment by diocrap** [comment]
@Demon-tk in the video and the readme file it says to turn on dungeon types /seed finder types dungeon on

**Comment by DoomRater** [comment]
Is there some way I have to input this seed once I find it?  Because even after using the dungeon finder, and it displays a world seed in that fashion, I still get a seed number that doesn't match when I recreate it offline.  Tested on 1.16.5.

**Comment by KaptainWutax** [comment]
Go to the end or enable dungeons.
