### ISSUE TITLE
findshed search with no results

### ISSUE THREAD

**Issue by YinNue** [KaptainWutax/SeedCracker#163]
I'm at the terminal, waiting for the progress bar to pop up（findshed search with no results,reverting back to biomes）When I was in the main world, I saw the Red Square on the ground, so I went down to see the dungeon, but no matter how I ran, he couldn't load the seeds.The server I play on is multi world 1.16.4 technology server, but it should not be unable to load the main world and the terminal
![16118956293892370367732528286735](https://user-images.githubusercontent.com/66358524/106232897-209c5280-6230-11eb-8168-1d7a8d1296b6.jpg)

**Comment by YinNue** [comment]
Slime technology server

**Comment by YinNue** [comment]
I just ran the map in the end for a long time, he popped up a progress bar to load me seeds, but the main world did not work, I ran tens of thousands of tiles, and even found a triple dungeon, but did not pop up the seed acquisition.  At first I wondered if I ran the graph too fast. Later I stayed in Sanlian for about 10 minutes and still didn’t respond. I ran around and didn’t.

**Comment by 8bitFra** [comment]
I had a similar problem on a Paper server and it seems like it can't get it to work in any way (including dungeons). There does not seem to be any plugins aimed at blocking seed cracking and doing a little research on google I discovered that on spigot, it is possible to change the seeds of the structures and block this method of seed finding. Is there any way to make the mod work?



**(SERVER PLUGINS)**
![pl](https://user-images.githubusercontent.com/47214887/106782013-fdb3d900-6649-11eb-8231-273fdb20d0bf.png)

**Comment by KaptainWutax** [comment]
You probably just collected data from non-1.16 chunks.

**Comment by 8bitFra** [comment]
Anyway I knew this thing about 1.16 chunks. To be sure I tried very far from spawn (more than 100k) to be 100% sure I was in new chunks but nothing, same error! (Finished dungeon serach with no seeds.)
