### ISSUE TITLE
1.16.5 Update

### ISSUE THREAD

**Issue by Tiebe** [KaptainWutax/SeedCracker#164]
Will there be a 1.16.5 update for this?

**Comment by ottOMGadd** [comment]
1.16.5 is almost identical to 1.16.4 so probably not

**Comment by Tiebe** [comment]
It didn't work for me on 1.16.5

**Comment by 8bitFra** [comment]
Use 1.16.4, 1.16.5 fixed some very small bugs only on servers, you can enter any server with 1.16.4.

**Comment by nealmcb** [comment]
I noticed a proposed fix in PR #175 which seems to suggest a rendering issue, but I don't know the details.
See also likely dup at #164.

**Comment by j7168908jx** [comment]
It made me crashed on 1.16.5, so seemly not working?

**Comment by Tiebe** [comment]
> See also likely dup at #164.


This is #164 right?

**Comment by AntonHDMI** [comment]
you can't enter Minehut servere in 1.16.4 D:
