### ISSUE TITLE
Question: manually adding some structions on single player => they were not found. 

### ISSUE THREAD

**Issue by Meemoryk** [KaptainWutax/SeedCracker#165]
Hello, 
since generation of seed on latest paper version for End dimension is not working.
( End city and end Gateway structions are not found ) 

I decided to create new single player world and manually find structions on paper and copy them to my single player game.
at the begining it sounded like a good idea but when i have copied succesfully pillars and pillar seed was generated just fine i have found out that SeedCracker is not able to locate my Own created Ender City not even EndGateWay, i tried to search in your code but i didn't found nothing suspicious.

Could you please advise if what i tried to do is even possible or is there any crosscheck against different biom layers so you would be able to recognize manually added structions. 

Thank you in advance for your response.

Have a nice day
Best regards
Memory

**Comment by KaptainWutax** [comment]
You need to find intact structures.
