### ISSUE TITLE
Can't only disable Emerald_Ore

### ISSUE THREAD

**Issue by MaxLevs** [KaptainWutax/SeedCracker#169]
I am playing on a server with anti-xray plugin what pretends like there are a lot of ores around you. And SeedCracker detect emerald_ore blocks in this false-structures.
When I tried to disable emerald_ore detection with typing "/seed finder type emerald_ore off" and cleared data nothing changed, new emerald ore blocks was still found. If I disable whole decorations It worked, but if I tried enable only one type of decorations e.x. dungeons It tried to find emerald ore as well.

**Comment by KaptainWutax** [comment]
Clear the data and then disable it.

**Comment by MaxLevs** [comment]
I tried it. But when I enable e.x. dungeons, emerald_ore enables as well. I combined an order of this operations (clearing, disabling ore, disabling all decorations) and explained my results previous message.
For crack I wanna use decorations too (because amount of data is too small without emerald_ore) but without emerald_ore.

**Comment by zykrahgaming** [comment]
see #58
