### ISSUE TITLE
of.message.opengl error

### ISSUE THREAD

**Issue by Footsiefat** [KaptainWutax/SeedCracker#17]
I found a problem while using aristos that gave me an error message that said something like of.message.opengl error.
So I believe it cannot print text into my chat witch is a big problem. Any ideas?

**Comment by Earthcomputer** [comment]
That looks like an OptiFine problem. Does it work without OptiFine? If so, try reporting it to https://github.com/modmuss50/OptiFabric

**Comment by Footsiefat** [comment]
Will do, it works without opfine
