### ISSUE TITLE
I am using T launcher and its crashing whenever i try to open the game with seed cracker

### ISSUE THREAD

**Issue by ashiq115** [KaptainWutax/SeedCracker#174]
FIX THIS PLEASE

**Comment by charizard1596** [comment]
dont use tlauncher pay for the game

**Comment by AlphaMode** [comment]
If your playing on 1.16.5 there is a rendering issue that causes a crash you can check my fork which fixes the issue

**Comment by KaptainWutax** [comment]
1. Don't use TLauncher.
2. Don't use TLauncher.
3. Provide more details. 
4. Also, don't use TLauncher.

**Comment by MrAppu** [comment]
Technically, it worked for me in tlauncher
