### ISSUE TITLE
Getting (Fetched hashed world seed [*a random seed*]

### ISSUE THREAD

**Issue by snaxemjax** [KaptainWutax/SeedCracker#18]
I am trying the latest commit and whenever i load a world be it new or old i get "Fetched hashed world seed [seed]" But that seed is totally different from the correct seed.

**Comment by snaxemjax** [comment]
I am trying it on 20w09a.

**Comment by KaptainWutax** [comment]
Yes? It's the **HASHED** world seed. Not sure it can get any clearer.

**Comment by snaxemjax** [comment]
Sorry but i haven't done that heavy of a research on Minecraft seeds, may i know where i go from there?

**Comment by snaxemjax** [comment]
> 
> 
> Yes? It's the **HASHED** world seed. Not sure it can get any clearer.

Sorry but i haven't done that heavy of a research on Minecraft seeds, may i know where i go from there?

**Comment by elliotnash** [comment]
What is a hashed world seed? is there any way to convert it into a normal seed so I can create a world with the same seed?

**Comment by Neffc** [comment]
It's a hash of the world seed.

> is there any way to convert it into a normal seed so I can create a world with the same seed?

No, the hash is not useful on its own. The SeedCracker program uses it along with other decorator/structure information to calculate the world seed. The program is just notifying you that it obtained the hash, which is then stored for later use.

**Comment by elliotnash** [comment]
So how do you calculate the world seed with seed cracker? I've figured out how to locate structures but not how to find the world seed

**Comment by Neffc** [comment]
Check the readme, there's a video tutorial that explains it thoroughly
