### ISSUE TITLE
I get the hashed seed. Not The seed.

### ISSUE THREAD

**Issue by snaxemjax** [KaptainWutax/SeedCracker#19]
Yes? It's the **HASHED** world seed. Not sure it can get any clearer.

_Originally posted by @KaptainWutax in https://github.com/KaptainWutax/SeedCracker/issues/18#issuecomment-595188955_

So my issue is i got this

Hashed seed: 8522322698510382504
Actual seed: 7655431440644442769

Now, how do i get the actual seed from the hashed seed? (And yes i know it's the hashed seed i mean i can read) 

Edit: Here's what the output looks like and the output seed being different from the actual one https://imgur.com/a/UnQiPmM

Sorry if i sound like an arse not knowing about what the issue is. Until today i didn't even know what gradle was and how to even compile a mod jar from git.

Also, appreciate what you're doing here.

**Comment by KaptainWutax** [comment]
Could you please follow the instructions in the readme and/or the video tutorial. This is the hashed seed not the world seed, you can't do anything of major significance with it that the program doesn't already do.

**Comment by hube12** [comment]
Ok time to have a little course about hash then, here a nice video: https://youtu.be/S9JGmA5_unY , in a nutshell a cryptographic hash function can not be reversed from only one output without any knowledge about the original message or without bruteforcing all the seed space thus it's useless as it (we do not bruteforce usually we construct a full rainbow table for 2^64 which is dumb)

**Comment by snaxemjax** [comment]
I followed the video step by step and i do not get any additional messages after going to the end. The only message i get is of that hashed seed. And thank you @hube12 i did look into hash and why its really hard or some might say impossible rn to decode as its a one way concept. Thanks for the replies.

**Comment by hube12** [comment]
Did you collect enough structures?
Also, you are not using a release version so it could be broken.
This mod is a work in progress with full release for 1.14, 1.15 up to 1.15.2.

**Comment by snaxemjax** [comment]
I did collect enough structure data. I even tried with more than enough and less than recommended just to be sure. It could be broken that's the only thing i could think of.
