### ISSUE TITLE
Not collecting bits

### ISSUE THREAD

**Issue by ORB-Aerospace911** [KaptainWutax/SeedCracker#194]
Im using the 1.16.4 version with the fabric mod 1.16.4 on a paper Minecraft multiplayer server. I used /seed bits clear /seed finder DECORATIONS ON. Dungeons is also on. I see green out lines but I still have no bit. Any idea why it's not working?

**Comment by zykrahgaming** [comment]
could be anti-xray, see #58

**Comment by zykrahgaming** [comment]
I modified the mod in a way that makes using it on anti-xray enabled servers a lot easier: https://github.com/zykrahgaming/SeedCracker/releases/tag/v0.2.4-beta-modified
(It just disables emerald ore finder and enables dungeon finder by default)
