### ISSUE TITLE
multiplayer seed cracking

### ISSUE THREAD

**Issue by GuyKachur** [KaptainWutax/SeedCracker#2]
In new singleplayer worlds this has worked wonders! on multiplayer servers it doesnt seem to work, My working guess as to why is that it logs biomes around spawn based on blocks. Most spawns(unless you start with the world) are covered in all sorts of blocks and can mess that up. Is there any merit to this? I have tried multiple different structures & decorator features and nothing seems to give me a seed. Do certain structures have higher weights? Should i avoid areas that have been highly developed? Do more structures logged equal a higher success rate or does it stop getting more accurate after a certain number? If the seed matches are ranked if none are found could it output the closest couple? or is it all just Boolean?
Sorry for the barrage of questions and Thanks an absolute ton for the work, what a cool program!

**Comment by KaptainWutax** [comment]
Just before we get started, I'd like to say that I have tested it in multiplayer and it worked as well as singleplayer. Your issue is most likely caused by a server-side problem. So here's a few questions: is it a 100% vanilla server? Was part of the map generated in older versions(tons of decorators have changed in 1.15)? Did you try running the program without emeralds and dungeons?

**Comment by GuyKachur** [comment]
It was definitely made in an older version(1.14), and its a realm so both those could probably break everything. I tried using structures from 1.15 generated areas but spawn is spawn and the end is the end.  It is vanilla otherwise, not sure how you can even make realms anything else. I have run without emerald ore, not dungeons.

**Comment by KaptainWutax** [comment]
Emerald ore, dungeons, end gateways and biomes have all changed in 1.15. So what you wanna do is go to newly generated chunks and relog to reset the cracker.

**Comment by GuyKachur** [comment]
I can do that. Would it make sense to disable those options and try? I cant really get to the end without going through 1.14 chunks. (tho with the seed i hope to find my own end portal lol)

**Comment by KaptainWutax** [comment]
Yes, disable everything on your way to the end.

**Comment by GuyKachur** [comment]
Ill try that, and report back. Thanks!

**Comment by GuyKachur** [comment]
Well I've tried that a few times, doesn't seem to work. I'm chalking it up to realms are weird, and am gonna try it a few more times with different structures / combinations of things later and report back if anything works

**Comment by GuyKachur** [comment]
Okay, so this is what i did that worked. I went out into new chunks in the overworld. Set my bed spawn. Then went into the end into new chunks. Re logged. Then explored a few end cities and gateways, went to the pillars. It found a bunch of seeds, then when i went to the overworld, it logged those biomes and found the correct seed!

**Comment by KaptainWutax** [comment]
Great news! I guess you still accidentally went through 1.14 chunks. Happy to hear it works now, enjoy!

**Comment by GuyKachur** [comment]
Thanks for the help!
