### ISSUE TITLE
Multiplayer Spawner/Dungeons not highlighted

### ISSUE THREAD

**Issue by adamantium1987** [KaptainWutax/SeedCracker#203]
on a SMP Paper server and Spawners and dungeons are not being highlighted.

**Comment by TwoPointInfinity** [comment]
dungeons are off by default. turn them on

**Comment by adamantium1987** [comment]
I have turned them on.

**Comment by adamantium1987** [comment]
Figured out the seed.

**Comment by adamantium1987** [comment]
I had dungeons turned on I used 19MiserX98 version and it found the seed.
