### ISSUE TITLE
Not finding the right seed

### ISSUE THREAD

**Issue by joelimgu** [KaptainWutax/SeedCracker#205]
Hello, I want to crack a seed from a server and it isn't giving me the right seed (paper spigot 1.16.5) but for testing purposes I logged on to my own server which has no anti-cheat plugins (spiggot 1.16.4) and it gives 2 different seeds to me and both are wrong. Any idea of what might cause this? 
Thank you for your time, if you need more information about it just ask.

**Comment by PhoenixXKN** [comment]
paperspigot has built-in seed cracking protection
