### ISSUE TITLE
The search doesn't complete

### ISSUE THREAD

**Issue by gabrielchl** [KaptainWutax/SeedCracker#21]
Below is the output of the mod, right after I spawned into the end:
```
Looking for pillar seeds...
Finished search with [33283] seed.
Looking for structure seeds with 12 structure features.
Looking for structure seeds with 28 decorator features.
Completed thread 1!
Completed thread 0!
Completed thread 3!
Completed thread 2!
Finished search with [106325158578193] seed.
Looking for world seeds with 15 biomes.
Finished search with [2680311053397444625] seed.
```
Then, it stops. No more output from the mod.

Structure features detected: 2 end cities, 1 ocean monument, 1 buried treasure, a few shipwrecks, and maybe some other features.

MC Version: 1.15.2

Expected behaviour: return seed or failure message.

**Comment by KaptainWutax** [comment]
2680311053397444625 is your world seed, congrats! :D

**Comment by gabrielchl** [comment]
Oh, my bad for not understanding the output :P Thanks a lot.

**Comment by gabrielchl** [comment]
Ummm I'm sorry but do you mind deleting this issue? I'm sorry for the inconvenience... :(

**Comment by KaptainWutax** [comment]
Nope, you're supposed to close the issue when you're done. It's all good man.

**Comment by gabrielchl** [comment]
Uh, the problem is that I realized that I shouldn't use this mod on a server I play on so I'm worried that someone might be able to see this :(
