### ISSUE TITLE
1.17

### ISSUE THREAD

**Issue by joogle12** [KaptainWutax/SeedCracker#216]
Hey, any estimation on when the 1.17 release will come out?

**Comment by elwo-boop** [comment]
yeah, how do i download the seedcracker for 1.17 anyways? i saw that you updated the code but im not sure how to download it without the release.

**Comment by joogle12** [comment]
> yeah, how do i download the seedcracker for 1.17 anyways? i saw that you updated the code but im not sure how to download it without the release.

I tried to build it but got bunch of errors. Try building it from source.

**Comment by MattJG77** [comment]
Please please please someone update this to 1.17.

**Comment by joogle12** [comment]
> yeah, how do i download the seedcracker for 1.17 anyways? i saw that you updated the code but im not sure how to download it without the release.

I built the jar from source. lemme know if you want it.

**Comment by joogle12** [comment]
> Please please please someone update this to 1.17.

I built the jar from source. lemme know if you want it.

**Comment by FunsizeGamer** [comment]
> > Please please please someone update this to 1.17.
> 
> I built the jar from source. lemme know if you want it


> > Please please please someone update this to 1.17.
> 
> I built the jar from source. lemme know if you want it.

Plz i need it

**Comment by ThePro1604** [comment]
> > Please please please someone update this to 1.17.
> 
> I built the jar from source. lemme know if you want it.

hey can u send the jar for the 1.17 please?

**Comment by MattJG77** [comment]
> > Please please please someone update this to 1.17.
> 
> I built the jar from source. lemme know if you want it.

Yes please. I have no idea how to compile anything. how can i contact you off this thread?

Plus everyone needs this file. I wish the author would just add it to the releases downloads.

**Comment by joogle12** [comment]
@ThePro1604 @MattJG77 @elwo-boop @FunsizeGamer 

hey guys. I will upload it to a GitHub fork of this project in a few hours. I'll let you know when I do.

**Comment by joogle12** [comment]
@ThePro1604 @MattJG77 @elwo-boop @FunsizeGamer 

Hey guys! I have created the 1.17 release. here is the link.
https://github.com/joogle12/SeedCracker/releases/tag/1.17-release

**Comment by ThePro1604** [comment]
> @ThePro1604 @MattJG77 @elwo-boop @FunsizeGamer
> 
> Hey guys! I have created the 1.17 release. here is the link.
> https://github.com/joogle12/SeedCracker/releases/tag/1.17-release

Thank You!

**Comment by joogle12** [comment]
joogle#0607 on discord

**Comment by joogle12** [comment]
> > > Please please please someone update this to 1.17.
> > 
> > 
> > I built the jar from source. lemme know if you want it.
> 
> Yes please. I have no idea how to compile anything. how can i contact you off this thread?
> 
> Plus everyone needs this file. I wish the author would just add it to the releases downloads.

joogle#0607 on discord

**Comment by joogle12** [comment]
> > @ThePro1604 @MattJG77 @elwo-boop @FunsizeGamer
> > Hey guys! I have created the 1.17 release. here is the link.
> > https://github.com/joogle12/SeedCracker/releases/tag/1.17-release
> 
> Thank You!

does it work good? I haven't really tested it.

**Comment by IamNuggets** [comment]
> does it work good? I haven't really tested it.

It works Thanks for building the mod.
But You need to do the following to get it to work properly
/seed finder category STRUCTURES ON
/seed finder category BIOMES ON
/seed finder category DECORATORS ON

**Comment by TTVexoticfro** [comment]
Is this a fabric or forge mod?

**Comment by joogle12** [comment]
> Is the 1.17 version a fabric mod?

its a fabric mod

**Comment by noonegothere** [comment]
> @ThePro1604 @MattJG77 @elwo-boop @FunsizeGamer
> 
> Hey guys! I have created the 1.17 release. here is the link.
> https://github.com/joogle12/SeedCracker/releases/tag/1.17-release

when I load a world or join a server it says in chat
"Fetched hashed world seed [-8507650244553618542]

**Comment by HIHIQY1** [comment]
> 
> 
> > @ThePro1604 @MattJG77 @elwo-boop @FunsizeGamer
> > Hey guys! I have created the 1.17 release. here is the link.
> > https://github.com/joogle12/SeedCracker/releases/tag/1.17-release
> 
> when I load a world or join a server it says in chat
> "Fetched hashed world seed [-8507650244553618542]"
> the actual seed is 11111

That is intentional. The hashed world seed is not equal to the actual world seed.

**Comment by listenthelisten** [comment]
I don’t know why the client crashes suddenly when I use it on the server.

**Comment by joogle12** [comment]
> > @ThePro1604 @MattJG77 @elwo-boop @FunsizeGamer
> > Hey guys! I have created the 1.17 release. here is the link.
> > https://github.com/joogle12/SeedCracker/releases/tag/1.17-release
> 
> when I load a world or join a server it says in chat
> "Fetched hashed world seed [-8507650244553618542]"
> the actual seed is 11111

 You need to do the following to get it to work properly
/seed finder category STRUCTURES ON
/seed finder category BIOMES ON
/seed finder category DECORATORS ON

**Comment by joogle12** [comment]
> I don’t know why the client crashes suddenly when I use it on the server.

update ur fabric?

**Comment by Sulde** [comment]
> > > @ThePro1604 @MattJG77 @elwo-boop @FunsizeGamer
> > > Hey guys! I have created the 1.17 release. here is the link.
> > > https://github.com/joogle12/SeedCracker/releases/tag/1.17-release
> > 
> > 
> > when I load a world or join a server it says in chat
> > "Fetched hashed world seed [-8507650244553618542]"
> > the actual seed is 11111
> 
> You need to do the following to get it to work properly
> /seed finder category STRUCTURES ON
> /seed finder category BIOMES ON
> /seed finder category DECORATORS ON

Is it work with anti-Xray?

**Comment by MaxLevs** [comment]
> > > > @ThePro1604 @MattJG77 @elwo-boop @FunsizeGamer
> > > > Hey guys! I have created the 1.17 release. here is the link.
> > > > https://github.com/joogle12/SeedCracker/releases/tag/1.17-release
> > > 
> > > 
> > > when I load a world or join a server it says in chat
> > > "Fetched hashed world seed [-8507650244553618542]"
> > > the actual seed is 11111
> > 
> > 
> > You need to do the following to get it to work properly
> > /seed finder category STRUCTURES ON
> > /seed finder category BIOMES ON
> > /seed finder category DECORATORS ON
> 
> Is it work with anti-Xray?

Yes, it does. It just checks blocks around you and tries to find structure's ones. And when it collected enough for cracking, starts process. It can take some time but usually it works fine. If not, try to change configuration. Sometimes anti-Xray can place fake ores here and there but another ways is still works.

**Comment by MaxLevs** [comment]
> @ThePro1604 @MattJG77 @elwo-boop @FunsizeGamer
> 
> Hey guys! I have created the 1.17 release. here is the link.
> https://github.com/joogle12/SeedCracker/releases/tag/1.17-release

I have some problem with starting mc with your build
```The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'seedcracker'!
Exit Code: 255
```

**Comment by Sulde** [comment]
> > > > > @ThePro1604 @MattJG77 @elwo-boop @FunsizeGamer
> > > > > Hey guys! I have created the 1.17 release. here is the link.
> > > > > https://github.com/joogle12/SeedCracker/releases/tag/1.17-release
> > > > 
> > > > 
> > > > when I load a world or join a server it says in chat
> > > > "Fetched hashed world seed [-8507650244553618542]"
> > > > the actual seed is 11111
> > > 
> > > 
> > > You need to do the following to get it to work properly
> > > /seed finder category STRUCTURES ON
> > > /seed finder category BIOMES ON
> > > /seed finder category DECORATORS ON
> > 
> > 
> > Is it work with anti-Xray?
> 
> Yes, it does. It just checks blocks around you and tries to find structure's ones. And when it collected enough for cracking, starts process. It can take some time but usually it works fine. If not, try to change configuration. Sometimes anti-Xray can place fake ores here and there but another ways is still works.

Sorry looks like wont work with dungeons 
Is warped forest available?

**Comment by hugoalves6** [comment]
> > @ThePro1604 @MattJG77 @elwo-boop @FunsizeGamer
> > Hey guys! I have created the 1.17 release. here is the link.
> > https://github.com/joogle12/SeedCracker/releases/tag/1.17-release
> 
> I have some problem with starting mc with your build
> 
> ```
> Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'seedcracker'!
> Exit Code: 255
> ```

Same over here with forge mod loader, even tried with fabric api and still the same error
[crash-2021-06-22_21.37.52-client.txt](https://github.com/KaptainWutax/SeedCracker/files/6697278/crash-2021-06-22_21.37.52-client.txt)

**Comment by joogle12** [comment]
> > > > > > @ThePro1604 @MattJG77 @elwo-boop @FunsizeGamer
> > > > > > Hey guys! I have created the 1.17 release. here is the link.
> > > > > > https://github.com/joogle12/SeedCracker/releases/tag/1.17-release
> > > > > 
> > > > > 
> > > > > when I load a world or join a server it says in chat
> > > > > "Fetched hashed world seed [-8507650244553618542]"
> > > > > the actual seed is 11111
> > > > 
> > > > 
> > > > You need to do the following to get it to work properly
> > > > /seed finder category STRUCTURES ON
> > > > /seed finder category BIOMES ON
> > > > /seed finder category DECORATORS ON
> > > 
> > > 
> > > Is it work with anti-Xray?
> > 
> > 
> > Yes, it does. It just checks blocks around you and tries to find structure's ones. And when it collected enough for cracking, starts process. It can take some time but usually it works fine. If not, try to change configuration. Sometimes anti-Xray can place fake ores here and there but another ways is still works.
> 
> Sorry looks like wont work with dungeons
> Is warped forest available?

I think SeedcrackerX has that. Not 100% sure tho. Use that if this doesn't work.

**Comment by joogle12** [comment]
@MaxLevs @hugoalves6 
Use SeedCrackerX or try building it yourself if mine does not work. I don't know any solutions. =)

**Comment by joogle12** [comment]
@hugoalves6 @MaxLevs hey guys. I figured  out your problem. You had downloaded the wrong jar file. Download the 4th file instead of the first one. =)
