### ISSUE TITLE
Can I manually input seeds for 20w11a?

### ISSUE THREAD

**Issue by BritainIS** [KaptainWutax/SeedCracker#22]
I read in #1 that an issue with the profiler (I assume you mean the one on the debug screen) was causing the mod to break. Would it be possible to manually enter coordinates of various structures and biomes as well as the coordinates and height of the end pillars and then run the mod with that? Thanks.

**Comment by KaptainWutax** [comment]
Neil has a standalone program that can do this: https://github.com/hube12/MinecraftSeedCrackingC/releases. I don't plan to add support for manual inputs since the whole point of the mod is to eliminate user error.
