### ISSUE TITLE
When 1.17

### ISSUE THREAD

**Issue by AngelFireLA** [KaptainWutax/SeedCracker#222]
I've been waiting but there isn't any version for 1.17 even tought in the source code there is a mention of 1.17 (not the release)

**Comment by SmallPepperZ** [comment]
There is a 1.17 version, but it hasn't been precompiled. You can build it yourself with the source code and https://github.com/KaptainWutax/SeedCracker#building-the-mod

**Comment by joogle12** [comment]
Hey. I made one here few weeks ago. https://github.com/joogle12/SeedCracker/releases/tag/1.17-release

**Comment by p0ndobear** [comment]
it doesnt work tho

**Comment by joogle12** [comment]
> it doesnt work tho 
> 
> I've tried it on like 6 worlds the seed is always wrong

The hashed world seed is not the actual one. You have to walk around more and visit more biomes.

**Comment by yuanmo618** [comment]
> There is a 1.17 version, but it hasn't been precompiled. You can build it yourself with the source code and https://github.com/KaptainWutax/SeedCracker#building-the-mod

I run the gradlew.bat but found no jar file, where can i find it?

**Comment by SmallPepperZ** [comment]
> > There is a 1.17 version, but it hasn't been precompiled. You can build it yourself with the source code and https://github.com/KaptainWutax/SeedCracker#building-the-mod
> 
> I run the gradlew.bat but found no jar file, where can i find it?
You have to download the repository source code, then build it with `./gradlew build`

**Comment by joogle12** [comment]
> > There is a 1.17 version, but it hasn't been precompiled. You can build it yourself with the source code and https://github.com/KaptainWutax/SeedCracker#building-the-mod
> 
> 
> 
> I run the gradlew.bat but found no jar file, where can i find it?


You have to do /gradlew build or ./gradlew build in your terminal. It should be in build and then libs folder. The actual mod is the largest file.

**Comment by IceWaffles** [comment]
> Hey. I made one here few weeks ago. https://github.com/joogle12/SeedCracker/releases/tag/1.17-release

Does this work in 1.17.1?

**Comment by CB30** [comment]
> > Hey. I made one here few weeks ago. https://github.com/joogle12/SeedCracker/releases/tag/1.17-release
> 
> Does this work in 1.17.1?

yeah
