### ISSUE TITLE
Why am I being returned no seeds?

### ISSUE THREAD

**Issue by xKirtle** [KaptainWutax/SeedCracker#23]
I've rendered a lot of structures and decorators yet it still returns me no seeds once I get in the end.
It works flawlessly in a single player world but I can't make it work on this server for some reason.
![Ccdsin1jbi](https://user-images.githubusercontent.com/30240961/77838685-12902800-716e-11ea-80bf-cf2a0c6bb5a0.png)

I've seen some old issues and although I'm not sure the map was generated all in 1.15.2, most of the structures I found were for sure generated in 1.15.2 (I found lava that didn't flow to the bottom since it had not been rendered). Any idea? Thanks a lot!

**Comment by NintendoBest** [comment]
In some servers, (idk the exact reason and how) But the Overworld Seed is not the same seed of the End.
Like recently, my server reseted the end and the seed.

So "Finished search with [62461] seed." Should be your End dimension seed. (I may be wrong)
If your server do not have the original Overworld and End seed together, your result will be what you got.
You can only search for the End Seed at this point. Still useful though.
*Correct me whoever if i'm wrong

**Comment by xKirtle** [comment]
> In some servers, (idk the exact reason and how) But the Overworld Seed is not the same seed of the End.
> So "Finished search with [62461] seed." Should be your End dimension seed. (I may be wrong)
> If your server do not have the original Overworld and End seed together, your result will be what you got.

I checked on an [End City Finder](https://www.chunkbase.com/apps/endcity-finder#62461) and the End Cities don't match so I guess that's not quite right. My current guess is that they generate parts of the map with different seeds? I've definitely went far enough to get structures on the latest map seed but if those don't match the End Pillars, there's no point, right? If we were able to get the world seed without the End Pillars, maybe it would work but I don't know how necessary they are in the cracking process.

**Comment by KaptainWutax** [comment]
62461 is the pillar seed, nothing you can do with it unless you know what you're doing. If you wanna find the end world seed on Paper you're gonna have to locate end cities, end gateways and the pillars. Once the seed cracking process finishes, the "structure seed" would be the one.

**Comment by xKirtle** [comment]
Would it be possible for me to get current Overworld seed if the End Pillars were created under a different seed than the one that currently generates new structures?

**Comment by KaptainWutax** [comment]
Nope, the mod doesn't support that currently. But working on it. See #14.
