### ISSUE TITLE
dificulties with 1.17.1

### ISSUE THREAD

**Issue by phant0m2290** [KaptainWutax/SeedCracker#233]
so doesn't matter what. i cant build the 1.17.1 version. i've tried everything. can someone send me the 1.17.1 build

**Comment by zaBees** [comment]
1. extract the zip file, when you have downloaded the master zip thingy
2. where the file location is written type cmd
3. type gradlew build and press enter
4. wait for it to finish
5. check the build file it's somewhere there
or just download it from me
[seedcracker-0.2.3-beta.zip](https://github.com/KaptainWutax/SeedCracker/files/7160519/seedcracker-0.2.3-beta.zip)

**Comment by kaytitulaer2008** [comment]
> 1. extract the zip file, when you have downloaded the master zip thingy
> 2. where the file location is written type cmd
> 3. type gradlew build and press enter
> 4. wait for it to finish
> 5. check the build file it's somewhere there
>    or just download it from me
>    [seedcracker-0.2.3-beta.zip](https://github.com/KaptainWutax/SeedCracker/files/7160519/seedcracker-0.2.3-beta.zip)

yea. the problem is. my cmd says gradlew isnt a command. but i have installed gradle

**Comment by phant0m2290** [comment]
> 1. extract the zip file, when you have downloaded the master zip thingy
> 2. where the file location is written type cmd
> 3. type gradlew build and press enter
> 4. wait for it to finish
> 5. check the build file it's somewhere there
>    or just download it from me
>    [seedcracker-0.2.3-beta.zip](https://github.com/KaptainWutax/SeedCracker/files/7160519/seedcracker-0.2.3-beta.zip)

**Comment by phant0m2290** [comment]
thx :)

**Comment by GreatGodOfFire** [comment]
When I try to run /seed version 1.17.1 it says `ur bad, git gud syntax` so it seems like it doesn't support 1.17
