### ISSUE TITLE
Turn Rendering Off by Default

### ISSUE THREAD

**Issue by MildKid** [KaptainWutax/SeedCracker#24]
Is there a way to turn rendering off so that I don't have to keep using the `/seed render off` command every time I restart my game?

**Comment by KaptainWutax** [comment]
No there isn't and I do not plan to ever do that.

**Comment by ShayBox** [comment]
Change your plan then because it's quite annoying

**Comment by vktec** [comment]
The way I see it, SeedCracker is a mod that should only be enabled when you actually want to use it, and when you do the renderer is useful more often than not.
If you don't already have a way to easily disable mods, I recommend checking out [MultiMC](https://multimc.org/).

**Comment by KaptainWutax** [comment]
> Change your plan then because it's quite annoying
> 
> That and it requiring mixed casing because of your case sensitive commands and lack of response to invalid commands

1. This is a one time use mod and am I serious with keeping it that way. If you find it annoying then don't use it.
2. Case sensitiveness comes from Brigadier and is a conscious decision on Mojang's part. Report your lame annoyance for it here: https://github.com/Mojang/brigadier.
3. What lack of response to invalid commands? Is it that hard to press TAB and ENTER repeatedly?
