### ISSUE TITLE
1.18?

### ISSUE THREAD

**Issue by itschasa** [KaptainWutax/SeedCracker#242]
title

**Comment by buiawpkgew1** [comment]
@KaptainWutax Update！

**Comment by itschasa** [comment]
agreed

**Comment by HappyDoggyTW** [comment]
agreed

**Comment by jktechs** [comment]
Agreed

**Comment by ZaneJulienMOI** [comment]
Guys you know that this is gonna take a while to update because the entire world generation was changed in 1.18, so he probably has to configure the entire thing

**Comment by itschasa** [comment]
> Guys you know that this is gonna take a while to update because the entire world generation was changed in 1.18, so he probably has to configure the entire thing

yes but update

**Comment by ggtylerr** [comment]
If you want 1.18 support *now*, go learn Java and Fabric. Otherwise, wait and stop begging.

**Comment by itschasa** [comment]
> If you want 1.18 support *now*, go learn Java and Fabric. Otherwise, wait and stop begging.

never was begging for it lmfao

**Comment by ggtylerr** [comment]
> > If you want 1.18 support *now*, go learn Java and Fabric. Otherwise, wait and stop begging.
> 
> never was begging for it lmfao

It's a general message for everyone on this issue and for people asking for it.

**Comment by efindus** [comment]
Here is a working fork with 1.18 support: [https://github.com/19MisterX98/SeedcrackerX](https://github.com/19MisterX98/SeedcrackerX)

**Comment by buiawpkgew1** [comment]
@itschasa https://github.com/19MisterX98/SeedcrackerX/releases
