### ISSUE TITLE
Performance improvement and cannot find seed

### ISSUE THREAD

**Issue by noodlychezzy** [KaptainWutax/SeedCracker#25]
Is there any way I could improve my performance whilst using this? I'm getting super low FPS when trying to fly around searching for data.
Is there a way I can disable the outlines of blocks that class as "data" for the cracker?
thanks

Also, when trying to crack the seed, it shows a seed for the structures and decorators, but it says `seed cannot be found` when it gets to the biome part
I went to 300+ decorators, ~5 structures and ~23 biomes.

I think the problem is the same as #14 because the server has a lobby when you first join
Thanks

**Comment by KaptainWutax** [comment]
Performance is something I've been fighting against since the start. I tried my best to off-load the finders to another thread but I understand this causes issues on lower-end computers with a low core count. For now, I would suggest turning off the dungeon finder since it's the most straining one by FAR.

**Comment by KaptainWutax** [comment]
Once you find a structure seed you've basically reversed the entire seed. I cannot tell you why biome search fails(well it should have used the hashed seed anyway, are you on the latest release?) but from the top of my head, this could have happened:
- You collected biome data in pre 1.15 chunks.
- The server is running a different biome generator (large biomes, amplified, default_1_1, etc).

**Comment by noodlychezzy** [comment]
The server was made a couple days ago, so pre 1.15 chunks aren't an issue
I'm sure biome generators are the same

so I guess the problem is the problem in #14 
would it be difficult to make a toggle?
thanks for responding

**Comment by KaptainWutax** [comment]
It would make the codebase complicated for not much. I've implemented a way to clear data though that should be in the next release for 1.16.
