### ISSUE TITLE
Please make 1.17.1

### ISSUE THREAD

**Issue by AnandBhasme** [KaptainWutax/SeedCracker#250]
The mod is great! But please make one for 1.17.1

**Comment by buiawpkgew1** [comment]
> The mod is great! But please make one for 1.17.1

https://github.com/19MisterX98/SeedcrackerX/releases/tag/2.9

**Comment by AnandBhasme** [comment]
> > The mod is great! But please make one for 1.17.1
> 
> https://github.com/19MisterX98/SeedcrackerX/releases/tag/2.9

Yeah I found SeedCrackerX that day later. I forgot remove the above comment but Thanks for replying though :D
