### ISSUE TITLE
Finder Profile is locked.

### ISSUE THREAD

**Issue by Shiroah** [KaptainWutax/SeedCracker#27]
Hey, been using this mod for ~2 days now, I'm on a paper 1.15.2 server and I've got the hashed world seed, but whenever I try to enable anything in the finder, it returns me this error:
"Your current finder profile is locked and cannot be modified. Please make a copy first."

Is that problem due to Windows limiting which program can or can't access files or is it something I need to manually do?

**Comment by KaptainWutax** [comment]
You seem to be using an unreleased version. Please make sure to only get your jars from https://github.com/KaptainWutax/SeedCracker/releases.
