### ISSUE TITLE
Cannot get any seed

### ISSUE THREAD

**Issue by Killerqu00** [KaptainWutax/SeedCracker#30]
Currently trying to get a seed of a Minecraft 1.15.2 Paper server, it was on this version from the very beginning.
I tried to investigate structures like buried treasures, underwater ships and spawners, but I cannot get any seed. Is some specific combination of structures and decorators required?

**Comment by KaptainWutax** [comment]
Paper has some seed cracking protection. The end and overworld seeds are different so the pillars mess up the search. In the latest release v0.1.0-beta I have added an experimental feature to cracks seeds with only the overworld. Enable it via `/seed finder type DUNGEON ON`.

**Comment by Killerqu00** [comment]
OK, thank you very much, I'll test it tomorrow.

**Comment by JClouseau42** [comment]
Question: I'm also on a server with seemingly different seeds between overworld and End (get different hash values).  When turning on this feature (dungeon) how do you trigger the seed cracking routine without using the End pillars (/seed finder type END_PILLARS OFF)?  Seems without turning pillars off the routine is still trying to use their gen in the calculations.

**Comment by Killerqu00** [comment]
Ok, that worked. Thanks a lot! Sorry, but I will delete the screenshot bc it  can be used against me.

**Comment by Killerqu00** [comment]
By the way, is there any method to get "end seed" or something like that? If I understand correctly, Paper just generated End dimension with different seed:does it mean that I can just find a few end structures then come back to pillars and get seed of the world where end dimension is the same as on the server?
