### ISSUE TITLE
Seed Not Displaying (Even With Dungeon)

### ISSUE THREAD

**Issue by sproga2** [KaptainWutax/SeedCracker#31]
I appear to have everything set up with this mod correctly, as I'm getting outlines and such, but I'm confused as to how the dungeon finder addition helps. I'm attempted to get a server's seed without going to the end (they have a different end seed), yet even turning on the dungeon finder hasn't changed anything.

It's been on for a  while. I cleared the bits. I have 535 out of 32 bits. No seed has been found (or started to be found as far as i can tell). Should I just be getting an overwhelming amount of bits for it to work without the end?

**Comment by sproga2** [comment]
Wait, I'm an idiot and just needed more data.

**Comment by mememasterlord32345** [comment]
how many bits did you have to get?
