### ISSUE TITLE
"Finished dungeon search with no seeds."

### ISSUE THREAD

**Issue by sproga2** [KaptainWutax/SeedCracker#32]
I just tried a few dungeon searches (no end pillars due to a different seed being used for the end). The first couple produced seeds that did not equal the server's seed, and the last few I've tried have resulted in the error listed in the title of my issue post. I've tried a few different combinations of finders to no positive effect. Any suggestions?

The exploring was done entirely in 1.15 chunks. The border was only expanded for 1.15, so I stuck next to it until I got results.

![2020-05-01_22 54 31](https://user-images.githubusercontent.com/11450137/80853455-14328d00-8bff-11ea-926e-e65346a13434.png)

**Comment by KaptainWutax** [comment]
Is the dungeon floor intact?

**Comment by lmijler** [comment]
i have the same error
