### ISSUE TITLE
1.12.2 (with ViaVersion)

### ISSUE THREAD

**Issue by postout** [KaptainWutax/SeedCracker#34]
Testing this on a server running 1.12.2 using a 1.15.2 client to connect with ViaVersion support. My understanding was that dungeon seeding hadn't been changed since 1.12.2, but am I wrong thinking that? Upon logging in, I get a message that SeedCracker has "fetched hashed seed [0]", and the dungeon search returns no results. 

The finders locate decorators correctly, and I've tried running with no other finders except dungeons, and combinations of other finders without Biomes, but with no luck. Is there a way for me to use this on a 1.12.2 ViaVersion server? Is there something I'd need to change in the DungeonFinder.java file to support this?

**Comment by KaptainWutax** [comment]
Only structures and pillars will work. Backporting everything else is a monumental pain, I'm not willing to offer support for it.

**Comment by postout** [comment]
Understood. I'd love to fork it and backport the dungeon finder myself, do you have any resources that would give me an idea of what math would need changed?

**Comment by KaptainWutax** [comment]
I could guide you through it but it's seriously a non-trivial thing to do.

**Comment by KaptainWutax** [comment]
It's hard to explain things here since there's no proper documentation but I can help you in the Monkeys discord: https://discord.gg/7P3nqzZ.

**Comment by Arenovas** [comment]
Darn, quite a shame you can't support older versions. And I take it there's no way, or at least no easy way, to add a sort of version select for seeds so you could scan a 1.13 world or something with 1.15?

**Comment by KaptainWutax** [comment]
I could but that's more effort than I'm willing to put into it.

**Comment by Mobmaker55** [comment]
If you needed something done with 1.12.2, there are plenty of other tools that should serve you better. Most tools are still based around the 1.9-1.12.2 scene, as that was one of the larger times where seed cracking was the same (algorithmically).  

I'd recommend [Legertje64's seed cracker](https://www.reddit.com/r/technicalminecraft/comments/8pmqq7/legerts_l64_fast_seed_cracker_reverse_seed_finding/) if you are using a 1.12.2-based server. All of the directions are there on the link, best of luck.

**Comment by Arenovas** [comment]
Well that's a shame. And yeah that program won't help me much sadly since the world I'm trying to get a seed from is 1.13 and it doesn't have the end island so no end towers. But it has plenty of dungeons, shipwrecks, a few villages, and a desert well.
Any places that could potentially help me with figuring this seed out? Perhaps that Discord linked earlier or nah?
