### ISSUE TITLE
A couple suggestions

### ISSUE THREAD

**Issue by friendlytherapist** [KaptainWutax/SeedCracker#37]
1. Custom command that collects hashed world seed.
Reason: Clearing all seed data removes hashed world seed as expected, but the only way to get it back is by going to another dimension.

2. Custom command that lists all `types` and their values. ( Shipwrecks is set to TRUE, End Gateways is set to FALSE, ect.. )
Reason: its difficult to know what is enabled and disabled at a glance

3. Listing of old true and flase values. ( Set Shipwrecks to TRUE, old value FALSE )
Reason: its difficult to know what is enabled and disabled at a glance

These are mostly ease of use commands to make using the mod easier

**Comment by KaptainWutax** [comment]
You can't just request the hashed seed on demand sadly. I've also been working on a GUI to make all of this clearer.

**Comment by friendlytherapist** [comment]
Sounds good
