### ISSUE TITLE
Game crash and spamming world seed

### ISSUE THREAD

**Issue by loicbersier** [KaptainWutax/SeedCracker#38]
Client: 1.15.2 on linux using openjdk version "1.8.0_242"
mod installed: fabric-api-0.10.1+build.307-1.15, Wurst-Client-v7.1.2-MC1.15.2, seedcracker-0.1.0-beta 
server 1.14.4 paper using ViaVersion

When trying to get the overworld seed with the dungeon it freeze the game and spam the logs with a bunch of world seed

[latest.log](https://github.com/KaptainWutax/SeedCracker/files/4616638/latest.log)
Here the complete log of that session ( most of it is a "found world seed" spam )

I have been able to reproduce it 100% of the times
Step to reproduce:
1. Go to nether
2. /seed data clear
3. disable every category
4. enable dungeon finding
5. go to overworld
6. search around for dungeon

**Comment by KaptainWutax** [comment]
Since the server is 1.14.4 the hashed seed will be wrong and cause the biome search to explode. And even if it didn't explode it wouldn't have worked anyway. I only support 1.15.X servers, you're on your own.
