### ISSUE TITLE
Several questions

### ISSUE THREAD

**Issue by dadodasyra** [KaptainWutax/SeedCracker#39]
1) I saw in the closed issues that it is possible to find the seed without going into the end (in any case from what I understood, message in question: https://github.com/KaptainWutax/SeedCracker/issues/30#issuecomment-622552687_), I tried but nothing happened when I executed the command except give structure seeds. How to do ?

2) Will the mod be up to date when 1.16 is released?

**Comment by KaptainWutax** [comment]
1. Once you find structure seeds you need the hashed seed to complete the search. Either die or change dimensions for it to be fetched.

2. Yes, when 1.16 is released.
