### ISSUE TITLE
1.14 Questions

### ISSUE THREAD

**Issue by StinkyTako** [KaptainWutax/SeedCracker#4]
Hey, I watched Neil's video and tried using his earlier methods to no success. I was wondering if you could briefly explain how to get it to work on 1.14 since you said that it was meant for 1.14 in the beginning. If not then all is good.

**Comment by KaptainWutax** [comment]
I do not plan to offer support for 1.14. You can clone the repo right before the 1.15 update and compile it yourself though.

**Comment by StinkyTako** [comment]
That's a shame considering I have literally no idea how to do that :D thanks for the time though.

**Comment by hube12** [comment]
here what i compiled by using 0a4694d00b86f32f6e26c58634483816820390c7 with b24d540bb455d88a3fb228c7f3e1ea02dadb3a49


[libs.zip](https://github.com/KaptainWutax/SeedCracker/files/4003647/libs.zip)

**Comment by StinkyTako** [comment]
So this should work for 1.14 theoretically?
