### ISSUE TITLE
Cracker Progress ?

### ISSUE THREAD

**Issue by Mobmaker55** [KaptainWutax/SeedCracker#42]
Is there any way to know the progress of the cracker / when the operation starts? the /seed data bits command says I have more than enough (5207 bits out of 32), so I know that that's not the issue. I just noticed that my CPU is barely being used, nor my GPU. Is there something specific I have to do for it to crack the seed?

Also, is there a way for me to see the seed again after it finishes?

**Comment by KaptainWutax** [comment]
I was gonna say have you read the documentation just to realize I accidentally took it out while updating it. You need to locate the end pillars.

**Comment by Mobmaker55** [comment]
I did everything that should need to be done to start the render, including reaching the end pillars. I did not climb up each tower, though. I just stood on the ground in the center of the End Island. I also did not kill the dragon and jump back through the portal, if that's anything. I just jumped off the End Island... would that cause any issues?

Oh, I should also mention that I didn't go everywhere in one session. I constantly opened and closed my client, if that messes up the program at all.

**Comment by KaptainWutax** [comment]
Stuff is no saved. As soon as you leave the world it restarts.

**Comment by aria1th** [comment]
Actually seed cracking can be done without end dimension, by dungeon finder (that was nice), and respawn / go to nether. But in few cases, it does not work. and... there is no support for re-opening the session(I guess). As I tried in 20w18a, you should go and explore as much, in one session. when I restart minecraft(or launcher), it tries to solve it once more.

**Comment by Neffc** [comment]
> I did everything that should need to be done to start the render, including reaching the end pillars. I did not climb up each tower, though. I just stood on the ground in the center of the End Island. I also did not kill the dragon and jump back through the portal, if that's anything. I just jumped off the End Island... would that cause any issues?

The tender should start as soon as the pillars are all loaded. Has the bedrock on the end pillars been changed in the world you're testing?

**Comment by Mobmaker55** [comment]
Oh. The End took a giant crap on itself when it was generated, all of the pillars are off-Z by one block. That might be why it doesn't work at all. I've tried other programs, and even tried my own program I had designed for seed cracking. I thought that my program was at fault, but it might just be this world.

Also, if data isn't saved, how does it remember my bit count?

**Comment by KaptainWutax** [comment]
It... doesn't.

**Comment by Mobmaker55** [comment]
So I got 5207 bits just by joining the world? Now I'm more confused as to how that even happened...

**Comment by KaptainWutax** [comment]
It doesn't seem impossible to me. Worlds have a lot of data.

**Comment by Mobmaker55** [comment]
So TL;DR I have to go back to the End. Thanks!
