### ISSUE TITLE
Not picking up dungeons 

### ISSUE THREAD

**Issue by 12Testing3** [KaptainWutax/SeedCracker#46]
The mod isnt picking up dungeons. I think the model has been changed server side, anyway to modify how dungeons are recognized?

**Comment by Neffc** [comment]
The dungeon finder is off by default. Did you enable it?

**Comment by 12Testing3** [comment]
yes it is on, Ive tried other servers but it seems that dungeons have been modified using a spigot plugin

**Comment by KaptainWutax** [comment]
I can't do anything about it if it has been modified.
