### ISSUE TITLE
Not working at all(detail in desc)

### ISSUE THREAD

**Issue by Footsiefat** [KaptainWutax/SeedCracker#47]
So I first tried Neils old seed cracked for up to 1.14 with the following data:

[https://cdn.discordapp.com/attachments/510201738003873793/723344366474887228/coordshope.png](https://cdn.discordapp.com/attachments/510201738003873793/723344366474887228/coordshope.png)

-195 124 end city
356 1139 outpost
291 1091 buried treasure
311 1101 desert temple?
456 1312 village?
499 1414 outpost
529 1452 village?
547 1476 village?
586 1486 buried treasure
646 1545 buried treasure
634 1546 buried treasure
649 1604 buried treasure
650 1585 ocean monument southeast
-5456 -13257 end city

7460 21887 river
7463 21891 wooded hills
7502 21893 forest
7509 21892 plains
7685 22159 wooded mountians
7711 22158 swamp

And it couldnt find any seeds, I also tried with only buried treasure as well as some other things but that didnt work.

Then I tried this seed cracker and this didnt work, I first enabled all the structures and stuff and got 83/32 bits then teleported to the end, it couldnt find a seed.

Then I tried again with dungeons disabled, and got ~42/32 bits and then teleported to the end and it still couldnt find the seed.

[https://media.discordapp.net/attachments/510201738003873793/723398879537790977/2020-06-19_16.47.20.png?width=1995&height=1122](https://media.discordapp.net/attachments/510201738003873793/723398879537790977/2020-06-19_16.47.20.png?width=1995&height=1122)

This server is running on a 1.15.2 waterfall snapshot

If there are any logs I can provide please tell me where i can find them.

**Comment by Footsiefat** [comment]
Update, supposedly the admin fiddled with the highs off the end pillars and according to https://github.com/KaptainWutax/SeedCracker/issues/12 I can crack it without the end pillars, could you run me through how I would do this?

**Comment by KaptainWutax** [comment]
Have you tried dungeons?
