### ISSUE TITLE
[Suggestion] Structure/biome locator

### ISSUE THREAD

**Issue by CWKevo** [KaptainWutax/SeedCracker#48]
Hi,

I enjoy your mod a lot - I can finally get seeds of my favourite servers in like 10 minutes. Thank you so much for your effort put into this project.

I have 1 suggestion though - structure locator. Currently, the structures are located only if the chunk is loaded/if player is near it. My suggestion is that structures could always be located once the seed was found (even at far distances in unloaded chunks, like +1000 blocks). This would make my life when locating a specific structure easier. Maybe the mod could even show the name of the structure and draw a line (tracer) to them. You could adjust settings in a GUI (for example, toggle tracers, input seed if you already know it to locate structures), or at least by commands, such as `/seed structurefinder setseed <seed>` and it starts locating structures automatically, or adjust the search radius by `/seed structurefinder radius <radius in blocks/chunks>`. Along with that there could also be a biome locator etc, etc...

Online websites such as this one (https://www.chunkbase.com/apps/) already offer a way to locate structures & biomes, so it shouldn't be a problem to implement this feature in your mod, in my opinion.

Thank you,
 `-` CW

**Comment by Neffc** [comment]
> Online websites such as this one (https://www.chunkbase.com/apps/) already offer a way to locate structures & biomes, so it shouldn't be a problem to implement this feature in your mod, in my opinion.

Feel free to make a pull request, then. This is hardly a trivial addition, and would probably be better suited for an entirely different mod. The goal of this mod isn't to locate structures, but to crack the seed. There are other tools for that.

**Comment by CWKevo** [comment]
Understood, but thank you anyways!
