### ISSUE TITLE
Having trouble on servers.

### ISSUE THREAD

**Issue by master0fspades** [KaptainWutax/SeedCracker#49]
I've found all 5 structures and biomes, but the chat says I can't find the end pillar seeds. Any help?

**Comment by Neffc** [comment]
If the server owner has modified the towers at all, or generated the End dimension in a different version, you won't be able to get the end pillar seed. Try using the dungeon method, see the change log for instructions.

**Comment by master0fspades** [comment]
Well it just started searching but it keeps saying "finished search with no results" each time it tries to search

**Comment by KaptainWutax** [comment]
You're probably running it on old terrain.
