### ISSUE TITLE
SMP question

### ISSUE THREAD

**Issue by PeteArmstrong** [KaptainWutax/SeedCracker#5]
For servers that appear to have a different End seed and Overworld seed, is there a way to obtain the OW seed? Obtaining the End seed works fine, by just re-logging in the End and finding a few End Cities and then flying to the main island. But locating overworld features and then going into the end always fails. I've tried it with things like Ores and Igloos and Shipwrecks turned off, no luck. And I've made sure to find an end portal far away from any explored chunks.

**Comment by KaptainWutax** [comment]
Check out #2, it should cover your question. :D

**Comment by PeteArmstrong** [comment]
Yes I read that one several times and followed the solution that the other
person found. That's how I was able to get the end seed. The difference
between his experience and mine was that it solved for the end seed, and
that seed does work correctly for the end (I can locate cities correctly).
However that seed does not work in the overworld (the biomes are all wrong).

I didn't see this issue discussed in #2. If it's there and I missed it, my
apologies.

The server was newly reset for 1.15, and I'm only exploring chunks that are
far away from spawn, but the conclusion I'm coming to so far is that the
server is using some sort of obfuscation whereby they have a different seed
for the end and OW.

**Comment by KaptainWutax** [comment]
I am unsure with what you call end and overworld seed...there is only one seed and it's the world one.

**Comment by PeteArmstrong** [comment]
Yes that's what I thought as well. However, I was able to get a seed when I
used the cracker 100% in the end, and that seed works correctly for the end
but it doesn't work for the overworld. Some googling suggests that some
servers use a different seed to generate the OW and the end, possibly as an
obfuscation technique.

**Comment by KaptainWutax** [comment]
>  I was able to get a seed when I used the cracker 100% in the end, and that seed works correctly for the end but it doesn't work for the overworld.

You mean you found the world seed but when you generate a world with it it looks different?

**Comment by PeteArmstrong** [comment]
Correct. The end is 100% correct, but the overworld is all different.

**Comment by KaptainWutax** [comment]
That's probably just because it was generated in an older version.

**Comment by PeteArmstrong** [comment]
A follow-up to this issue: I tried to solve with the "OTHER" category turned off, to disable solving for anything in the end (pillars etc). However, when I entered the end and flew around the main island the solver did not start. I hopped through the exit portal to see if that would trigger it but it did not. 

Is the solver designed to only start if End Pillars are enabled?

**Comment by KaptainWutax** [comment]
Yes, the end pillars are required.

**Comment by PeteArmstrong** [comment]
Is it possible to change the solver so that it doesn't use the pillars for solving, only overworld features? Or is the search algorithm specifically designed to use the pillar locations in some way (i.e., to help limit the search range).

**Comment by KaptainWutax** [comment]
The seed cracker would take days/weeks without the end pillars so I didn't bother implementing that.

**Comment by PeteArmstrong** [comment]
Got it, makes sense.

**Comment by Rosskaman** [comment]
Is it possible to get enough biomes/structures that it also wouldnt take that long without end pillars? Or would it take days anyway?

**Comment by hube12** [comment]
There is ofc an external tool that take about 1 to 4 hours (depending of your gpu assuming last gen) here: https://github.com/hube12/Finders/releases (There will be no support tho, but it's not really hard to figure it out)
