### ISSUE TITLE
Not an issue, but...

### ISSUE THREAD

**Issue by JamieJohnsonson** [KaptainWutax/SeedCracker#50]
I really loved the mod in 1.15, and can't wait till it comes out for 1.16, so when can we expect it to come out for the new update?

**Comment by KaptainWutax** [comment]
When it's ready.

**Comment by hube12** [comment]
Hi, you mentionned 1.16.X, due to high demand this feature will come in the next few days/months.The less issues, the faster the dev can work. Enjoy a cup of tea 🍵 while waiting !
