### ISSUE TITLE
1.16.1 Update

### ISSUE THREAD

**Issue by MaximilianGaedig** [KaptainWutax/SeedCracker#51]
**I tried building it for 1.16.1 but it did not work, (obviously, what was I expecting) I only updated the versions of fabric and Minecraft. I can`t do anything more unfortunately cause I have no experience with making mods.**

**Here`s the error:**

`Caching disabled for task ':compileJava' because:
  Build cache is disabled
Task ':compileJava' is not up-to-date because:
  Task has failed previously.
All input files are considered out-of-date for incremental task ':compileJava'.
:setting java compiler args
Could not find refmap definition, will be using default name: SeedCracker-refmap.json
Full recompilation is required because no incremental change information is available. This is usually caused by clean builds or changing compiler arguments.
Compiling with JDK Java compiler API.
Note: SpongePowered MIXIN Annotation Processor Version=0.8
Note: ObfuscationServiceFabric supports type: "official:intermediary"
Note: ObfuscationServiceFabric supports type: "official:named"
Note: ObfuscationServiceFabric supports type: "intermediary:official"
Note: ObfuscationServiceFabric supports type: "intermediary:named"
Note: ObfuscationServiceFabric supports type: "named:official"
Note: ObfuscationServiceFabric supports type: "named:intermediary"
Note: ObfuscationServiceMCP supports type: "searge"
Note: ObfuscationServiceMCP supports type: "notch"
Note: Loading named:intermediary mappings from C:\Users\maxim\.gradle\caches\fabric-loom\mappings\net.fabricmc.yarn-tiny-1.16.1-5
Note: Writing refmap to C:\Users\maxim\Desktop\New folder\SeedCracker\build\classes\java\main\SeedCracker-refmap.json
Note: Writing refmap to C:\Users\maxim\Desktop\New folder\SeedCracker\build\classes\java\main\SeedCracker-refmap.json
Note: Writing named:intermediary output TinyMappings to C:\Users\maxim\Desktop\New folder\SeedCracker\build\loom-cache\mixin-map-1.16.1-5.tiny
C:\Users\maxim\Desktop\New folder\SeedCracker\src\main\java\kaptainwutax\seedcracker\cracker\storage\DataStorage.java:9: error: cannot find symbol
import net.minecraft.world.level.LevelGeneratorType;
                                ^
  symbol:   class LevelGeneratorType
  location: package net.minecraft.world.level
C:\Users\maxim\Desktop\New folder\SeedCracker\src\main\java\kaptainwutax\seedcracker\cracker\biome\GeneratorTypeData.java:4: error: cannot find symbol
import net.minecraft.world.level.LevelGeneratorType;
                                ^
  symbol:   class LevelGeneratorType
  location: package net.minecraft.world.level
C:\Users\maxim\Desktop\New folder\SeedCracker\src\main\java\kaptainwutax\seedcracker\cracker\biome\HashedSeedData.java:7: error: cannot find symbol
import net.minecraft.class_5217;
                    ^
  symbol:   class class_5217
  location: package net.minecraft
C:\Users\maxim\Desktop\New folder\SeedCracker\src\main\java\kaptainwutax\seedcracker\cracker\biome\GeneratorTypeData.java:10: error: cannot find symbol
        private static final Set<LevelGeneratorType> WHITELIST = ImmutableSet.of(
                                 ^
  symbol:   class LevelGeneratorType
  location: class GeneratorTypeData
C:\Users\maxim\Desktop\New folder\SeedCracker\src\main\java\kaptainwutax\seedcracker\cracker\biome\GeneratorTypeData.java:15: error: cannot find symbol
        private final LevelGeneratorType generatorType;
                      ^
  symbol:   class LevelGeneratorType
  location: class GeneratorTypeData
C:\Users\maxim\Desktop\New folder\SeedCracker\src\main\java\kaptainwutax\seedcracker\cracker\biome\GeneratorTypeData.java:18: error: cannot find symbol
        public GeneratorTypeData(LevelGeneratorType generatorType) {
                                 ^
  symbol:   class LevelGeneratorType
  location: class GeneratorTypeData
C:\Users\maxim\Desktop\New folder\SeedCracker\src\main\java\kaptainwutax\seedcracker\cracker\biome\GeneratorTypeData.java:23: error: cannot find symbol
        public LevelGeneratorType getGeneratorType() {
               ^
  symbol:   class LevelGeneratorType
  location: class GeneratorTypeData
C:\Users\maxim\Desktop\New folder\SeedCracker\src\main\java\kaptainwutax\seedcracker\cracker\biome\GeneratorTypeData.java:31: error: cannot find symbol
        public static boolean isSupported(LevelGeneratorType generatorType) {
                                          ^
  symbol:   class LevelGeneratorType
  location: class GeneratorTypeData
C:\Users\maxim\Desktop\New folder\SeedCracker\src\main\java\kaptainwutax\seedcracker\cracker\biome\source\EndBiomeSource.java:3: error: cannot find symbol
import net.minecraft.class_5217;
                    ^
  symbol:   class class_5217
  location: package net.minecraft
C:\Users\maxim\Desktop\New folder\SeedCracker\src\main\java\kaptainwutax\seedcracker\cracker\biome\source\EndBiomeSource.java:7: error: cannot find symbol
import net.minecraft.world.biome.source.TheEndBiomeSourceConfig;
                                       ^
  symbol:   class TheEndBiomeSourceConfig
  location: package net.minecraft.world.biome.source
C:\Users\maxim\Desktop\New folder\SeedCracker\src\main\java\kaptainwutax\seedcracker\cracker\biome\source\NetherBiomeSource.java:3: error: cannot find symbol
import net.minecraft.class_5217;
                    ^
  symbol:   class class_5217
  location: package net.minecraft
C:\Users\maxim\Desktop\New folder\SeedCracker\src\main\java\kaptainwutax\seedcracker\cracker\biome\source\NetherBiomeSource.java:7: error: cannot find symbol
import net.minecraft.world.biome.source.MultiNoiseBiomeSourceConfig;
                                       ^
  symbol:   class MultiNoiseBiomeSourceConfig
  location: package net.minecraft.world.biome.source
C:\Users\maxim\Desktop\New folder\SeedCracker\src\main\java\kaptainwutax\seedcracker\cracker\biome\source\OverworldBiomeSource.java:3: error: cannot find symbol
import net.minecraft.class_5217;
                    ^
  symbol:   class class_5217
  location: package net.minecraft
C:\Users\maxim\Desktop\New folder\SeedCracker\src\main\java\kaptainwutax\seedcracker\cracker\biome\source\OverworldBiomeSource.java:7: error: cannot find symbol
import net.minecraft.world.biome.source.VanillaLayeredBiomeSourceConfig;
                                       ^
  symbol:   class VanillaLayeredBiomeSourceConfig
  location: package net.minecraft.world.biome.source
C:\Users\maxim\Desktop\New folder\SeedCracker\src\main\java\kaptainwutax\seedcracker\cracker\biome\source\OverworldBiomeSource.java:9: error: cannot find symbol
import net.minecraft.world.level.LevelGeneratorType;
                                ^
  symbol:   class LevelGeneratorType
  location: package net.minecraft.world.level
C:\Users\maxim\Desktop\New folder\SeedCracker\src\main\java\kaptainwutax\seedcracker\cracker\biome\source\OverworldBiomeSource.java:15: error: cannot find symbol
        private final LevelGeneratorType generatorType;
                      ^
  symbol:   class LevelGeneratorType
  location: class OverworldBiomeSource
C:\Users\maxim\Desktop\New folder\SeedCracker\src\main\java\kaptainwutax\seedcracker\cracker\biome\source\OverworldBiomeSource.java:17: error: cannot find symbol
        public OverworldBiomeSource(long worldSeed, LevelGeneratorType generatorType) {
                                                    ^
  symbol:   class LevelGeneratorType
  location: class OverworldBiomeSource
C:\Users\maxim\Desktop\New folder\SeedCracker\src\main\java\kaptainwutax\seedcracker\cracker\biome\source\OverworldBiomeSource.java:34: error: cannot find symbol
        public LevelGeneratorType getGeneratorType() {
               ^
  symbol:   class LevelGeneratorType
  location: class OverworldBiomeSource
C:\Users\maxim\Desktop\New folder\SeedCracker\src\main\java\kaptainwutax\seedcracker\cracker\structure\StructureFeatures.java:8: error: cannot find symbol
import net.minecraft.world.gen.chunk.ChunkGeneratorConfig;
                                    ^
  symbol:   class ChunkGeneratorConfig
  location: package net.minecraft.world.gen.chunk
C:\Users\maxim\Desktop\New folder\SeedCracker\src\main\java\kaptainwutax\seedcracker\cracker\structure\StructureFeatures.java:12: error: cannot find symbol
        public static final ChunkGeneratorConfig CONFIG = new ChunkGeneratorConfig();
                            ^
  symbol:   class ChunkGeneratorConfig
  location: class StructureFeatures
Note: Writing refmap to C:\Users\maxim\Desktop\New folder\SeedCracker\build\classes\java\main\SeedCracker-refmap.json
Note: Writing refmap to C:\Users\maxim\Desktop\New folder\SeedCracker\build\classes\java\main\SeedCracker-refmap.json
Note: Writing named:intermediary output TinyMappings to C:\Users\maxim\Desktop\New folder\SeedCracker\build\loom-cache\mixin-map-1.16.1-5.tiny
20 errors`

**Comment by Neffc** [comment]
You'd need to actually update the mappings, not just try building it with a newer version

**Comment by ayyybe** [comment]
As Neffc said, the yarn mappings need to be updated as well and the code has to be adapted to the 1.16 mappings.

It's not perfect, but you can check out my fork [here](https://github.com/ayyybe/SeedCracker) for a temporary working 1.16.1 version. As long as you don't need to find dungeons or nether biomes it should work just fine for now.

**Comment by hube12** [comment]
Hi, you mentionned 1.16.X, due to high demand this feature will come in the next few days/months.The less issues, the faster the dev can work. Enjoy a cup of tea 🍵 while waiting !
