### ISSUE TITLE
[Suggestions] - Show cracked seed , log and GUI

### ISSUE THREAD

**Issue by Majklzbastlirny** [KaptainWutax/SeedCracker#53]
First of all, thank for this great mod. Now for the suggestions. 
It would be great, if you can type something like /seed show or similar to show cracked seed, because of my fast scrolling chat on server.
Second suggestion of mine is some kind of log , that would contain name of world/server and all necesary data for that world (location of structures, seed etc.). 
My last suggestion is some kind of GUI. Just gui version of commands which are already implemented.
I know coding is hard job, but I believe you can do it.

Thank you, 
MB

**Comment by KaptainWutax** [comment]
I'm in no rush to implement such things and already have thought about them.
