### ISSUE TITLE
1.16.1 Support

### ISSUE THREAD

**Issue by EDNX3** [KaptainWutax/SeedCracker#54]
Is there any version planned that will include support for 1.16.1, or is there currently a working version for that version that I am not aware of?

I saw that there were some changes to some files in an update called "update to 1.16.1 and big refactor part 1".  Does this version support 1.16.1 and if so how should I go about downloading/running this version of the mod in Minecraft?

Thanks.

**Comment by KaptainWutax** [comment]
Wait for the release, it'll be ready when it's ready.

**Comment by EDNX3** [comment]
Thanks for the quick reply, I'm new to this shit :).
