### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by TwoPointInfinity** [KaptainWutax/SeedCracker#55]
Not sure if you have a forum or discussion board anywhere but man i just have to say thank you for this tool. You could totally sell this type of product for cheap . Amazing tool thank you. Cant wait for the 1.16 update as many server's seed changed with the update a long with world gen.

**Comment by KaptainWutax** [comment]
<3

**Comment by hube12** [comment]
Kap will definetly only sell the protection to server owner, best business model ever
