### ISSUE TITLE
Dungeon search finding no seeds

### ISSUE THREAD

**Issue by omen124** [KaptainWutax/SeedCracker#56]
I know I can't match the End to the overworld on my server so I have tried the overworld/dungeon method, not long after flying around and finding my first dungeon I get a message saying, "short-cutting to dungeons..." method and then "Finished dungeon search with no seeds."
It seems to trigger almost immediately after finding my first dungeon and I never get a seed from it.
Am I doing something wrong or is the dungeon method not 100% accurate/optimised?

**Comment by KaptainWutax** [comment]
That shouldn't happen... maybe try finding another dungeon.

**Comment by omen124** [comment]
After flying to another area, logging out of the server then back in and finding 5 dungeons it happened again, I will keep trying in different spots throughout the server.
Is there a way to get a log to help?

**Comment by KaptainWutax** [comment]
So you're saying it failed 5 times in a row?

**Comment by omen124** [comment]
No, I had to fly over 5 different dungeons before it found 1 and then did the big base target thing and started calculating.

I just tried again in another part of the world and it worked, after finding the first dungeon and I actually got a seed.

**Comment by KaptainWutax** [comment]
That's strange, but you got your seed at least.

**Comment by omen124** [comment]
Is there a way to copy the seed to the clipboard?

**Comment by hube12** [comment]
Could you post the seed as well as the coordinates, we would like to investigate

**Comment by omen124** [comment]
Sorry about the delay, my server was updating from 1.15.2 to 1.16.1 and I had issues getting back on.
I did initially find the seed 8714210825261364408 on the 1.15.2 server
Listing seeds in X/Y/Z

- **Fail** 6520/79/-450
- **Fail** 6536/87/-797
- **Success** on 1.15.2 but **Fail** when trying again on 1.16.1 5518/70/-3587
- Also nearby that gives a **different result** that forces back to the normal search algorithm (please see the attached picture https://imgur.com/zy36QPR) 5800/71/-3439

I have checked the seed and it matches the map I have been playing on, checked against several temples/dungeons positions with a map from the seed.

I hope this helps, if you need more data I will try my best to assist.

**Comment by hube12** [comment]
Using the cracker in different version generated terrain is not supported so this is intended behavior.
