### ISSUE TITLE
Multiplayer Server issue

### ISSUE THREAD

**Issue by LotionDude** [KaptainWutax/SeedCracker#57]
I've just downloaded the new 1.16.1 patch for this mod and tested it on a multiplayer server that started vanilla but switched to spigot and the mod seems to function normally, however when i enter the end dimension the mod does not recognise the bedrock on top of the obsidian pillars. however when i went into singleplayer and immediately went into the end dimension the mod highlighted the bedrock.

**Comment by KaptainWutax** [comment]
That doesn't happen in vanilla, the pillars are probably modified.

**Comment by LotionDude** [comment]
I asked on the spigot discord server and they claim they don't modify any of the pillars.. is there any chance i can manually input the bedrock positions?

**Comment by hube12** [comment]
Hi, you could simply use the dungeons by enabling them in /seed finder type DUNGEON ON 
You will then not be limited by the end.

**Comment by hube12** [comment]
Also i would recommend to generate the pillar again by respawning a dragon, if they dont respawn like the old (remaining) ones then its definetly modified

**Comment by LotionDude** [comment]
I did try respawning the dragon but it still did not work, however the dungeon finder did work, thank you soo much!
