### ISSUE TITLE
End pillars not detected in multiplayer

### ISSUE THREAD

**Issue by KMikeeU** [KaptainWutax/SeedCracker#59]
I have tested the mod in singleplayer and it works great, after gathering data, going to the end triggers the pillar bruteforcing and the seed is cracked in no time.
On a multiplayer server however, going to the end does nothing. It shows the hashed seed of the end, but doesn't seem to find any pillars. The enderdragon has already been fought, if that makes a difference. Is there a way to manually enter the pillar heights?

Edits: 
Mod version: v0.2.0-beta, Fabric for 1.16.1 (v0.8.8 b202-1.16.1)
No abnormalities in client log
Server running on Paper, version unknown
Pillars have not been modified, we even tried resummoning the dragon, which should reset the pillars.

**Comment by Ai-TaSAi** [comment]
Also having this issue.  On Minecraft Realms version 1.16.1.  It also returned a hashed seed but did not continue calculating afterward.  I thought it was a bug, so I cleared seed data, regathered all the info, and reentered the end.  Same result - hashed seed, no calculation.

**Comment by Neffc** [comment]
If the end pillars have been modified in any way by the server owner, the pillars won't be identified correctly.

**Comment by Ai-TaSAi** [comment]
The pillars were not modified - the dragon had been resummoned several times and none of the pillars mined.

I looked at the previous issues, and "/seed finder type DUNGEON ON" was a solution to the problem.

**Comment by Neffc** [comment]
Dungeon finders wouldn't have anything to do with end pillar detection.

**Comment by zykrahgaming** [comment]
It doesnt detect end pillars for me either

**Comment by KaptainWutax** [comment]
A lot of people have been complaining about the end pillars not getting detected so I'm willing to take a look into it. Could you give me the coordinates of the 10 bedrock blocks, please?

**Comment by vdsk** [comment]
33, 85, -25
42, 94, 0
33, 88, 24
12, 91, 39
-13, 103, 39
-34, 82, 24
-42, 79, -1
-34, 76, -25
-13, 97, -40
12, 100, -40

I'm having the same issue, here are the coords of the bedrock blocks

**Comment by KaptainWutax** [comment]
Have you managed to get the seed too? It can help me if you did but not necessary.

**Comment by vdsk** [comment]
> 
> 
> Have you managed to get the seed too? It can help me if you did but not necessary.

Yes, the overworld seems to be accurate however the end structures seem to be off 
8729319489913601684

**Comment by KaptainWutax** [comment]
Ouch, then it's not helpful, thanks anyway. I'll check if those pillars coords are correct.

**Comment by KaptainWutax** [comment]
The expected pillar coordinates are:
42, 0
33, 24
12, 39
-13, 39
-34, 24
-42, -1
-34, -25
-13, -40
12, -40
33, -25

**Comment by KaptainWutax** [comment]
Those seem to match, interesting.

**Comment by zykrahgaming** [comment]
if im not wrong, the X and Z coordinates of the end pillars are always the same, its the Y coordinate that changes.

**Comment by KaptainWutax** [comment]
Yep, but the mod doesn't pick up on the pillars if the x and z coordinates don't match that's why I went checking those first.

**Comment by KaptainWutax** [comment]
Another question... can the mod spot end cities?

**Comment by Devansh-bit** [comment]
No wutax, it isnt spotting cities and gateways

**Comment by Devansh-bit** [comment]
Same problem though 😢

**Comment by KaptainWutax** [comment]
Ohhhh that's great then! It's not specific to the pillars.

**Comment by zykrahgaming** [comment]
Well i don't think it's necessarily great, but it does make things easier to figure out lol

**Comment by KaptainWutax** [comment]
C'mon it's just a block game, this will definitely save me quite some time. I think I already know what the problem is. :P

**Comment by Devansh-bit** [comment]
bLoCk GaMe 😝

**Comment by KaptainWutax** [comment]
![image](https://user-images.githubusercontent.com/36993134/86534891-3ae49c80-beaa-11ea-86dc-fefe58645cdd.png)
As expected... in MP hasEnderDragonFight() is false so it doesn't detect it as the end. Well, I gotta figure out a better way to do this.

**Comment by KaptainWutax** [comment]
Incredible DimensionType refactoring Mojang, 100% works. xD

**Comment by zykrahgaming** [comment]
maybe using infiniburn or whatever that is?

**Comment by KaptainWutax** [comment]
Yea... well there are better ways to do it but I can't be bothered. I'll use the infiniburn identifier.

**Comment by KaptainWutax** [comment]
Alright, that's fixed. I'll make a release later today or tomorrow. Thank you all for your help. 👍

**Comment by zykrahgaming** [comment]
Is the release coming out soon? its been over a day :(

**Comment by KMikeeU** [comment]
This seems to work

```java
public boolean isEnd(DimensionType dimension) {
        return !dimension.isUltrawarm() && !dimension.isBedWorking();    
}
```
