### ISSUE TITLE
Stop gathering data bits after turning off EMERALD finder 

### ISSUE THREAD

**Issue by kevindaze** [KaptainWutax/SeedCracker#60]
Since the server I played on has anti Xray hack, I need to turn off Emerald finder to get the cracker work properly.
I've typed /seed data clear then /seed finder type EMERALD_ORE OFF, but my cracker stop gathering data bits from biome and structure.
There's still highlight of those biome and structure block, however the number of /seed data bits still remains 0 and won't rise

**Comment by zykrahgaming** [comment]
I also have this issue...

**Comment by zykrahgaming** [comment]
To be clear, the server uses 1.16.1 paperMC's anti-xray which can be found in the paper.yml file, last i checked, incase you want to test for yourselves.

**Comment by KaptainWutax** [comment]
Biomes don't contribute to the bit count.
