### ISSUE TITLE
Not working in launcher

### ISSUE THREAD

**Issue by theunluckyone** [KaptainWutax/SeedCracker#62]
I am currently using the LauncherFenix for minecraft. I have tried to find the problem to not loading the seedcracker.jar being in the mods carpet or in the Fabric loader carpet (inside the mods carpet). I used the seedcracker version for 1.14, but every time I create a new world to try the Cracking it doesn´t work. It open the game with the Fabric loader version of 1.14.4.
 Sorry my English, I am a Latin American. This is the page of the Launcher: (https://launcherfenix.com.ar/wope/)

**Comment by KaptainWutax** [comment]
Buy the game
