### ISSUE TITLE
/seed data clear clearing finders

### ISSUE THREAD

**Issue by Devansh-bit** [KaptainWutax/SeedCracker#63]
Hey!
I am runnning into a problem with the data clear command.
When I enter my server's world, I need to clear data collected (Due to antixray). After clearing, I change the emerald ore finder to false and start the search. But still, some of the detected ore (between clear and turning finder off) stays and messes up the data.

If you could add a command for clearing only the data and not the finders, I can clear the data after changing the finders i want to modify....
Coding is hard and doing it for no gain is even harder and I understand. Sorry if I bothered you

**Comment by hube12** [comment]
Do /seed cracker OFF -> /seed data clear -> /seed finder type DUNGEON ON -> /seed cracker ON

**Comment by hube12** [comment]
also clearing the finder doesnt clear the config, it clear the queue so all the rendered blockw but if you move it will display new ones
