### ISSUE TITLE
Not working on multiplayer?

### ISSUE THREAD

**Issue by Arnioch** [KaptainWutax/SeedCracker#64]
I collected over 5k bits, then went to the end, and nothing happened. Is this because the end was already beaten by other people before I came in?

**Comment by hube12** [comment]
We recommend using the dungeon technics and not using the end one, please bear in mind that you need to enable dungeon with /seed finder type DUNGEON ON beforehand.

If the end doesnt success, try respawning the dragon, the pillar might have been broken, if that doesnt work, you have a custom end and need to rely only on the dungeon method.

**Comment by Arnioch** [comment]
Thanks

**Comment by Arnioch** [comment]
Nevermind, I found out. Thanks for all your help!

**Comment by KMikeeU** [comment]
I already wrote an issue for this today (#59) It will be fixed soon

**Comment by KaptainWutax** [comment]
That's fixed in release 0.2.1.
