### ISSUE TITLE
Unknown issue with dungeon skip

### ISSUE THREAD

**Issue by reecepounder** [KaptainWutax/SeedCracker#65]
Hello. I was hoping you'd be able to help me figure out what is the matter.

I turned on all the search options via category, and proceed thousands of blocks out to generate new, 1.16.1 chunks, as well as trying in spawn chunks which may be 1.15.2.

It detects the dungeons nearby, and finds several structure seeds. However, it instantly tells me it found no results for world seeds.

![image](https://user-images.githubusercontent.com/53270052/86620745-df3e1000-bf8a-11ea-9216-7d1d8c050d8f.png)
I am on a multiplayer Paper server - could this be the issue?

**Comment by KaptainWutax** [comment]
Seems like those are old chunks to me. 1.16 changed dungeons again so make sure to find new ones.
