### ISSUE TITLE
Not giving me the seed

### ISSUE THREAD

**Issue by JamieJohnsonson** [KaptainWutax/SeedCracker#67]
Ok, so I collected 10k bits and even reset the end pillars, but after the seed cracker is done loading, it gives an error message saying that no results were found.

I've tried multiple times before resetting the pillars and it still displayed the same message. Any suggestions?

**Comment by vdsk** [comment]
> 
> 
> Ok, so I collected 10k bits and even reset the end pillars, but after the seed cracker is done loading, it gives an error message saying that no results were found.
> 
> I've tried multiple times before resetting the pillars and it still displayed the same message. Any suggestions?

Are you on a vanilla server?

**Comment by JamieJohnsonson** [comment]
I'm on a Spigot server, if that's the reason, do you have any recommendations on what I should do to obtain the seed?

**Comment by vdsk** [comment]
Turn on dungeon structures with /seed finder type DUNGEON ON and go around looking for dungeons.

Spigot servers use a different seed by default for the overworld and end, the seed you get by turning this option on will be the overworld seed.

**Comment by JamieJohnsonson** [comment]
It worked! Thank you so much!

**Comment by scouttiger** [comment]
small question, i followed these steps but i get a errormessage when using the dungeons. it says it cant find an seeds using this option either. Is there any reason why i wouldnt be able to crack the seed? both ways are not working.

I am on a waterfall (paper) server btw

**Comment by KaptainWutax** [comment]
Use 1.16 chunks.

**Comment by SoldierBoy-alt** [comment]
Hell Kaptain,

I was trying to crack the seed on a 1.16 server created 2 days ago, so there should be no pre-1.16 chunks. It's a Waterfall (Paper) server, and it seems like they have some kind of masking which prevents your seed cracker from working. I disabled Emerald Ore in case it was an anti-xray feature messing with the cracker, but it returns no results on a Dungeon Search. I'm unable to do an End Pillar search as Spigot uses a different seed for the End and the Overworld. Please find attached my attempt.
![seed](https://user-images.githubusercontent.com/68377565/87660170-8aeb1b00-c756-11ea-970b-a78207f2e611.png)

**Comment by KaptainWutax** [comment]
Can't help you much. That dungeon is either faked or modded.
