### ISSUE TITLE
SeedCracker mod (0.2.1-beta) will not calculate the server seed if multiplayer server use some anti xray mod

### ISSUE THREAD

**Issue by AlanAnonymous** [KaptainWutax/SeedCracker#69]
SeedCracker mod (version: 0.2.1-beta) will not calculate the server seed after returning a hashed seed if multiplayer server (version: 1.16.1) use some anti xray mods such as Orebfuscator and Mirage. 

'Orebfuscator modifies data that are sent to clients to hide blocks of your choice, such as ore, chests, dungeons, etc.'
'AntiXray modifies the packets before they are sent to the players to prevent malicious users from viewing hidden ores in your world.'

I guess this kind of mods will send the wrong emerald ore location info to the player so that SeedCracker will show the wrong emerald ore location (light green cube) and gather the incorrect info.
Therefore, I try to clear the data first, then turn DUNGEON to ON and turn EMERALD_ORE to OFF. However, SeedCracker only regather the data rather than calculate seed.

**Comment by Devansh-bit** [comment]
Please watch the video carefully before posting an issue

**Comment by hube12** [comment]
This is a non issue, please disable the seedcracker while doing the changes.

/seed cracker OFF
/seed data clear
/seed finder type DUNGEON ON
/seed finder type EMERALD_ORE OFF
/seed cracker ON

( you might need to change dimension or kill yourself to get the hashed seed again)

**Comment by zykrahgaming** [comment]
@AlanAnonymous Check #58
