### ISSUE TITLE
Seed Cracker finding a massive amounts of seeds

### ISSUE THREAD

**Issue by PolarUgle** [KaptainWutax/SeedCracker#72]
So I used it and it started gathering a lot of seeds, and after it found structure seed in end it stopped
I ran GPU cracker in the background, however, I can't see how this would affect things.
one thing is I think the server is extreme hill biomes. 
and the nether was reset for 1.16 so that might also confuse the game. 

![2020-07-13_01 23 06](https://user-images.githubusercontent.com/55811105/87258922-bdbbb780-c4a7-11ea-8fd3-d2eb3d148fea.png)5.17.png…]
![2020-07-13_01 13 14](https://user-images.githubusercontent.com/55811105/87258925-beece480-c4a7-11ea-9b7f-
![2020-07-13_01 05 17](https://user-images.githubusercontent.com/55811105/87258932-d5933b80-c4a7-11ea-9db1-bcfebe6f061c.png)

**Comment by PolarUgle** [comment]
![2020-07-13_01 13 14](https://user-images.githubusercontent.com/55811105/87259002-666a1700-c4a8-11ea-9d2e-1f62f55f2a82.png)
another picture

**Comment by PolarUgle** [comment]
nvm, think it was because i mixed 1.15 chunks and 1.16 chunks

**Comment by KaptainWutax** [comment]
Yea that would cause this issue.
