### ISSUE TITLE
Nether Fortress Option?

### ISSUE THREAD

**Issue by JamieJohnsonson** [KaptainWutax/SeedCracker#73]
Hello! So I was able to get the seed for the overworld on this server I play on, but they reset the nether to that using a different seed. Is there any way to find the seed using nether structures or some other method that is available now?

Thank you! Love the Seed Cracker!

**Comment by KaptainWutax** [comment]
Nether seed cracking a little more annoying but doable. Maybe one day if I'm feeling bored...

**Comment by JamieJohnsonson** [comment]
ok, hopefully, you get bored soon! lol
