### ISSUE TITLE
I get errorcodes every time the mod tries to crack the seed

### ISSUE THREAD

**Issue by scouttiger** [KaptainWutax/SeedCracker#75]
Goodday!

I've tried out the SeedCracker mod for about 3 hours now and for some reason the only thing it does is gving me these two errors:
-Finished search with no results, reverting back to biomes
-Finished dungeon search with no seeds

I've tried both mechanics, first the one with the end_pillars and then the one with the dungeons. i've done the cracking in a pat of the world that has not been modified by any players yet for as far as i have seen.

Is there anything that could cause these problems? it has succeeded in finding the hashed seeds as it is supposed to do and it did find the seed of the end_pillars the moment i got over there, so nothing wrong there.

while cracking using the pillars it cant find any structure seed like it is supposed to do, it just runs till its 100% and then tells me the first given error-code.

Anyone who knows?

**Comment by scouttiger** [comment]
I've tried doing it by starting in the end (killing myself and doing /seed data clear to get rid of other stored bits)
it found the pillar seed and cashed it. then i proceeded to do /home end which is a home ive set next to two end cities. It starts to look for structure seeds and finds two yet does not do anything with them (it just says it found structure seeds). Then i proceeded to do /home base which is a overworld home of mine. the moment i join the overworld i get the errorcode "Finished search with no results, reverting back to biomes" again as i got in my first attempts.

**Comment by scouttiger** [comment]
progress-update:

i've gotten the seed of the end by linking 4 endcities and combining them with the pillarseed.
weirdly enough its not the seed of the overworld. the dungeon method in the overworld is still disfunctional and giving me the error ive mentioned earlier

**Comment by KaptainWutax** [comment]
Use newly generated dungeons in 1.16 for it to work.

**Comment by scouttiger** [comment]
that explains a lot, thanks. 

so the dungeon-feature doesnt work, then why does the normal route that im used to not work? ive found the seed of the end and if i use a tool like chunkbase i do find all the end-cities on the corresponding locations, yet when using the seed on the overworld it doesnt work, so i think the seed is different (logically). is there a fix? or am i just doing something incredibly wrong

**Comment by scouttiger** [comment]
> that explains a lot, thanks.
> 
> so the dungeon-feature doesnt work, then why does the normal route that im used to not work? ive found the seed of the end and if i use a tool like chunkbase i do find all the end-cities on the corresponding locations, yet when using the seed on the overworld it doesnt work, so i think the seed is different (logically). is there a fix? or am i just doing something incredibly wrong.
> 
> I am using everything that is in the mod in the finder option. what are the key structures or decorators that ive got to enable? maybe ive got to much and one of the bits is wrong or something?

Anyone who might know this? Does the mod also check for biomes? because they do not show up as bits in /seed data bits the moment i find a new biome. also, does de biome checker need de pillars still? I found out that the end, nether and overworld all have different seeds to prevent people from cracking them, so it there any way in 1.15.2 to crack the seed fully in the overworld?

**Comment by scouttiger** [comment]
and,what does reverting back to biomes mean? that it only looks at the biome bits or something? and if thats the case, when does the computation start again? i've collected over 10k of data (all types except dungeons) and it hasnt started yet after trying to decode it using the pillars
