### ISSUE TITLE
Seed cracking doesn't start when entering the End.

### ISSUE THREAD

**Issue by LIME-S** [KaptainWutax/SeedCracker#76]
Our vanilla server seed Changed a few times, thats why i only turned on the seed cracker when moving through new chunks. i found about 1k bits and made sure to reset the pillars. but when entering the end i got no messages from the seed cracking mod.

**Comment by KaptainWutax** [comment]
Which version are you running?

**Comment by LIME-S** [comment]
I'm running version 0.2.1-Beta on a Minecraft 1.16.1  Fabric client
On a single player world it worked just fine. The problem just occurred on the server.

**Comment by KaptainWutax** [comment]
That's strange-- can I get the coordinates of the bedrock blocks on the pillars?
