### ISSUE TITLE
can cracking be done with biome data alone?

### ISSUE THREAD

**Issue by end-user** [KaptainWutax/SeedCracker#77]
I don't appear to be getting the correct seed.  When I check it against a chunkbase biome map, what I see in game and what the site says my biomes should be are not matching.  If the server is using different seeds for different dimensions, could I restrict the finder to biomes alone?  I would need a way to manually kick of cracking since it appears to only be based on end pillars.

**Comment by KaptainWutax** [comment]
You can't do seed cracking based on biomes alone.
