### ISSUE TITLE
Cracking the seed of an alpha world

### ISSUE THREAD

**Issue by CyborgCabbage** [KaptainWutax/SeedCracker#78]
I have a world save from alpha v1.2.3_04 and would like to get the seed that was used to generate it (the seed in the worlds NBT is corrupted / has been overwritten and doesn't generate the same terrain). However, after bringing the world forward to 1.16 and disabling everything except dungeons, it says it can't find the seed. Is this because of dungeon generation changing since that version? If so, is there any tool like this that could work for alpha versions? Sorry if this is the wrong place to ask this.

**Comment by KaptainWutax** [comment]
Try the standalone tool: https://github.com/hube12/DungeonCracker
