### ISSUE TITLE
Dungeon method currently not working

### ISSUE THREAD

**Issue by splipopgus** [KaptainWutax/SeedCracker#79]
I tried using this on a multiplayer server using a host called YAPFA? I looked around for a dungeon and found it but it told me that it couldn't locate a seed, so I turned off emerald ore (just in case) and ran off to find another dungeon, and I found one. The same thing happened, and I don't know how to fix it. If YAPFA is completely gibberish then I don't know how to find the server host, I could also try using the End as a way of obtaining the seed because I haven't been able to reach it. Doing /seed doesn't work as you need /op for that to work.  How would I be able to fix this issue to anybody's best of knowledge?

**Comment by KaptainWutax** [comment]
Use newly generated chunks for the dungeon finder. Pre-1.16 chunks don't work.

**Comment by splipopgus** [comment]
> Use newly generated chunks for the dungeon finder. Pre-1.16 chunks don't work.

How do you do that? I'm a moron when it comes to these things

**Comment by splipopgus** [comment]
> Use newly generated chunks for the dungeon finder. Pre-1.16 chunks don't work.

Ok, so I ventured out and tried to find a dungeon that I reckon hasn't been found, and I did but the same thing happened

**Comment by ThatGamerBlue** [comment]
I'm having the same issue on a world fully generated in 1.16.1
