### ISSUE TITLE
Collected lots of data but still no seed?

### ISSUE THREAD

**Issue by Tameflux** [KaptainWutax/SeedCracker#8]
Collected plenty of data and went to the end but still no seed? Am I doing something wrong?

![github](https://user-images.githubusercontent.com/59819444/72238365-bc620e80-359a-11ea-849b-540f314ecfbd.png)

**Comment by KaptainWutax** [comment]
Was the entire map generated in 1.15?

**Comment by Tameflux** [comment]
I'm pretty sure. Is there any way to check?

**Comment by aidancrane** [comment]
> Was the entire map generated in 1.15?

Mine wasn't, I'm guessing that's the problem then.

**Comment by KaptainWutax** [comment]
No, there isn't from the client. You're gonna have to run around in newly generated chunks.

**Comment by aidancrane** [comment]
Can I still use the same end/end portal or will that effect the results?

**Comment by KaptainWutax** [comment]
The end is all fine.
