### ISSUE TITLE
Emerald ore producing too many bits, unable to disable

### ISSUE THREAD

**Issue by AquaZet** [KaptainWutax/SeedCracker#80]
Here is the issue: When i come close to a mountains biome, there are lots of emerald ore. Once i do /seed data bits, it displays hundreds or even thousands of bits. The weird thing here is that:
1) If you have 32 bits, the bruteforcing may start depending on circumstances
2) If you have 48 bits, the bruteforcing starts with biomes
3) If you have 64 bits, you have the seed (very obvious, since all seeds are 64 bit)
How come i have more than 64 bits, hundreds or thousand of bits?

Also i can't disable the emerald ores. I do /seed finder type EMERALD_ORE OFF, i do /seed data clear, and after a few minutes of exploring, when i stumble accross emerald ores, the bits SKYROCKET to the hundreds or thousands, leading to the seed to not be found.

Any explanation for too many bits? Why can't it be disabled? It really makes it difficult to find a seed because once you see a mountains biome, the bits skyrocket always leading to the seed to not be found.

**Comment by KaptainWutax** [comment]
You've got it all wrong. To find the seed you need one of 2 things:
1. 32 or more bits of data + the end pillars.
2. A single dungeon.

**Comment by AquaZet** [comment]
> You've got it all wrong. To find the seed you need one of 2 things:
> 
> 1. 32 or more bits of data + the end pillars.
> 2. A single dungeon.


Thanks for your reply. Actually the end pillars aren't required, when i find a dungeon it just gives me the seed after 1 minute (very fast).
But the question here is why does emerald ore produces too many bits? And, more importantly, do the hundreds or thousands of bits alter the seedfinding process or not?

**Comment by KaptainWutax** [comment]
That's just how it is... emerald ore gives a lot of information to uniquely identify the seed. It doesn't alter the process in any way.
