### ISSUE TITLE
End pillar's bedrock not detected - endcity/gateway working

### ISSUE THREAD

**Issue by TwinShards** [KaptainWutax/SeedCracker#81]
Current seed cracker used: LATEST. 0.2.1-Beta
Issue: I enter the end and the pillars are not being detect.
Here is a video that may help you resolve the issue.

https://youtu.be/TU1BB9FOCjQ

*For some strange reason it is not managing to brute-force the overworld alone using spawners.
This may be caused because it pickup the hashed seed from the hub? (Or maybe because i'm on 1.16 while the server's world is from 1.13? I do not recall the world generation changed from 1.13 to 1.16 but i may be wrong)
See this, i started from the beginning so you have a view of everything:

https://youtu.be/p5cLgwn693k

**Comment by KaptainWutax** [comment]
If it can't find dungeon seed it means the chunks have been generated before 1.14. You want new 1.16 chunks to do it. For the end pillars I'm not sure, can you give me the coordinates of the bedrock blocks?

**Comment by TwinShards** [comment]
Understandable for the overworld then. so i guess i wont try to search using the overworld, the server still run1.13.2 x)
XYZ
12 97 -39
-12 88 -39
-33 82 -24
-42 100 0
-33 94 -24

-12 85 39
12 76 39
33 103 24
42 91 0
33 79 -24

**Comment by KaptainWutax** [comment]
Those end pillars are offset from where they are supposed to be. Sorry, but I can't do anything for you. 
> Could there be a command to start the brute-forcing even if i couldn't use -dungeon/end pillar for the search?
No... there is a reason why it doesn't start earlier... you don't wanna finish the search with millions of possible seeds.

**Comment by TwinShards** [comment]
Understood. Welp i guess i wont find the seed of this server using your mod. An absolute great mod you created for 1.15/1.16 though :D
