### ISSUE TITLE
Finished search with no results

### ISSUE THREAD

**Issue by ReggieBeverage** [KaptainWutax/SeedCracker#82]
Hi. So I believe I did everything right. I did follow the tutorial video for 1.16. The data I collected was a shipwreck, the End pillars and an End City. Everything seemed to work as intended until it came back with no results. I am unsure if perhaps I am doing something wrong. 
![2020-07-30_11 58 29](https://user-images.githubusercontent.com/45641125/88946147-e5a76b00-d25c-11ea-96f0-9a72abdab265.png)

**Comment by ulysses936** [comment]
I'm a user of this wonderful mod,
some servers use different seed to generate overworld and the end
so you can only use dungeons to get the seed of overworld(attention the hashed world seed you get in the beginning ,if it looks unusual,like 69,maybe your server install a plugin called AntiSeedCracker)
if u want to know where the end city is ,find 4 end city +pillar seed and make sure you never leave the end,
at the end of this you can get a structure seed ,use it on chunkbase to find endcity
