### ISSUE TITLE
How to bypass AntiSeedCracker

### ISSUE THREAD

**Issue by ulysses936** [KaptainWutax/SeedCracker#83]
https://www.spigotmc.org/resources/81495/
A new plugin "AntiSeedCracker" can change hashed world seed
So i can only get some structure seeds and "Finished search with no results, reverting back to biomes"

**Comment by KaptainWutax** [comment]
Wow, that is definitely not a fix to seed cracking lol. Since the counter is so easy I might as well just implement it. It's just cause I was lazy to use getBiomeForNoise() gen instead of getBiome(). The hashed seed check will fail but biomes will work, I'll see what I can do.

**Comment by KaptainWutax** [comment]
On top of not being a proper fix, Gaider here makes some good points about the data being the client and server being wrong: https://www.spigotmc.org/threads/antiseedcracker-1-15-1-16-x.451684/.

**Comment by ulysses936** [comment]
Thank you

**Comment by Ezzer29** [comment]
Does anyone know a 1.16 manual seed cracker then?

**Comment by Redapple-one** [comment]
AntiAntiSeedCracker XD
