### ISSUE TITLE
When I go into the world , it does not give me the hashed world seed

### ISSUE THREAD

**Issue by LIUXU2001** [KaptainWutax/SeedCracker#84]
How can I fix it?

**Comment by LIUXU2001** [comment]
i use 1.15.2 and seedcracker-0.1.0-beta

**Comment by KaptainWutax** [comment]
In 1.15 you need to switch dimensions or die to get the hashed seed.

**Comment by LIUXU2001** [comment]
Thanks a lot， bro！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "KaptainWutax/SeedCracker"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月7日(星期五) 凌晨1:56
收件人:&nbsp;"KaptainWutax/SeedCracker"<SeedCracker@noreply.github.com&gt;;
抄送:&nbsp;"unsigned"<1679498718@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [KaptainWutax/SeedCracker] When I go into the world , it does not give me the hashed world seed (#84)





 
In 1.15 you need to switch dimensions or die to get the hashed seed.
