### ISSUE TITLE
Enough bits but it doesnt start to search

### ISSUE THREAD

**Issue by qin33** [KaptainWutax/SeedCracker#87]
![Unbenannt](https://user-images.githubusercontent.com/69540568/89943789-0f7a6d80-dc1f-11ea-8f38-550c3b89ed0e.PNG)
 I found 1 ocean monument 3 shipwrecks 1 dungeon and 3 or 4 chests in beaches and it still wont start to search

**Comment by qin33** [comment]
One thing that may be an issue is that this server uses orebfuscator as anti xray plugin which makes all stone to mossy cobble and emerald ore, dia ore, gold ore and obsidian. However i set Emerald_ore to off so i doubt that this is an issue

**Comment by KaptainWutax** [comment]
You need the end pillars to start the search.
