### ISSUE TITLE
Seed cracker problem.

### ISSUE THREAD

**Issue by Darkenl** [KaptainWutax/SeedCracker#88]
It's saying "ur bad, git gud syntax". How do i fix this problem?

**Comment by KaptainWutax** [comment]
just git gud syntax

**Comment by Darkenl** [comment]
Yeah but how do i get gud syntax that's the problem.

**Comment by KaptainWutax** [comment]
Is it that hard to press tab and autocomplete the commands? You haven't really explained your issue.

**Comment by elCanarioVidal** [comment]
Hola, tengo el mismo problema, por más que escribo correctamente la sintaxis del comando me devuelve el mensaje _"ur bad, git gud sintax"_
Estoy usado la versión MC 1.16.5 y seedcracker-0.2.3-beta.jar.
No se qué problema podría ser.
Gracias!

**

> Google translation:

**
**Hello, I have the same problem, no matter how much I write the command syntax correctly, it returns the message _ "ur bad, git gud syntax" _
I am using MC version 1.16.5 and seedcracker-0.2.3-beta.jar.
I don't know what the problem could be.
Thanks!**

**Comment by frkboy** [comment]
do /seed date bits
