### ISSUE TITLE
What counts as what?

### ISSUE THREAD

**Issue by 23SRLITheGamer** [KaptainWutax/SeedCracker#9]
What structures count for structure features and what counts as decorator features?
i went around a smp and it didnt find a seed with 4 structure features, i know it needs 5, and 146 decorator features, and didnt find a seed.

Update: The center of the world 6500~ish is generated in 1.14 thats why it didnt work.

**Comment by vktec** [comment]
Structures are things like witch huts, jungle temples, ocean monuments, etc. Decorators are things like end gateways, emerald ore veins, etc.

**Comment by 23SRLITheGamer** [comment]
can i get a specific list of each? at least the more prominent ones, and what colors do each get represented by, like i know red is spawners, green is biomes, pink is temple or shipwrecks, and yellow for buried treasure. I do know that some structures dont count like in the video the igloo dont count but the jungle temple doesnt also show the box.

**Comment by KaptainWutax** [comment]
Oops, didn't see this, sorry for the late answer. The release page (https://github.com/KaptainWutax/SeedCracker/releases) shows what is what.
