### ISSUE TITLE
Confused

### ISSUE THREAD

**Issue by ASHER04** [KaptainWutax/SeedCracker#90]
So I believe I am following all steps accordingly and I read other people's problems. I collect enough bits with emerald ore disabled and dungeons on. After collecting enough I go to the end and it finds the pillar seed. It then begins looking for world seeds and almost immediately fails (keep in mind I /seed data clear before the start) and "Finished search with no results, reverting back to biomes." So it just gets stuck on "Looking for World seeds...". I am pretty lost what to do. 

EDIT: The server is 1.16.1 Paper.

**Comment by KaptainWutax** [comment]
Pillars don't work on paper, try dungeons instead.

**Comment by ASHER04** [comment]
So I just did that. I left the server then joined back thus refreshing everything. I turned the cracker on and turned off emerald ore, then I ran around a bit and no dice still.
