### ISSUE TITLE
How long does it take?

### ISSUE THREAD

**Issue by qblrafk** [KaptainWutax/SeedCracker#93]
I'm on a Paper 1.16 world and I'm wondering how long it will take to get the seed, I've been walking around for about 30 minutes and it says I have 1400 out of 32 bits collected and I have all the settings on. How long will this take or am I doing something wrong?

**Comment by KaptainWutax** [comment]
Use dungeons on paper. /seed finder type DUNGEON ON

**Comment by qblrafk** [comment]
Could you try it for me on the server? It's still not working

**Comment by qblrafk** [comment]
or can anyone here try it on a server for me the IP is survival.rteenagers.com

**Comment by qblrafk** [comment]
I got a bunch of structure seeds but the world seed still didn't come up, could I enter these structure seeds somewhere and find the seed? I went in new chunks aswell

**Comment by BellaMC** [comment]
I thought you had to enter the end to activate the seed searching.
