### ISSUE TITLE
what about mineshafts?

### ISSUE THREAD

**Issue by 1234r5** [KaptainWutax/SeedCracker#94]
im not an expert on either code nor how minecraft worlds are created but would it be possible to add a finder for mineshafts or cave spider spawners? sorry if im asking for the impossible but i thought i'd just ask to be sure :)

**Comment by KaptainWutax** [comment]
What would mineshafts provide that other structures and decorators don't?

**Comment by 1234r5** [comment]
Batches of cave spider spawners are extremely useful for wither rose farms, would be nice to have a finder for them

**Comment by KaptainWutax** [comment]
This is a seed cracker mod, not XRAY.

**Comment by 1234r5** [comment]
Yeah was kinda expecting that response, thanks for answering though :)
