### ISSUE TITLE
Build Failing

### ISSUE THREAD

**Issue by EmreM** [KaptainWutax/SeedCracker#96]
gradle build failed each time i attempted to build the repo (cloned latest commit since you ported it to 1.16.2 in a recent commit)

**Comment by hube12** [comment]
No it aint

**Comment by hube12** [comment]
while waiting for kap enjoy : https://github.com/hube12/SeedCracker/releases/tag/0.2.2-beta

**Comment by EmreM** [comment]
Thank you so much!!
