### ISSUE TITLE
Can't get overworld seed correct.

### ISSUE THREAD

**Issue by BellaMC** [KaptainWutax/SeedCracker#99]
I just did the dungeon method, I used the nether roof to go far out and find one.  I happened to spawn right next to one and it started the process.  It gave me this seed **1633266787** the one that it gave me in the end, Only problem is that this seed doesn't line up correctly, it is only in the nether (and end I think) are the same.

**Comment by KaptainWutax** [comment]
If it gave you a world seed then it can only be right.

**Comment by BellaMC** [comment]
it only matches in the nether and end, idk what happened
